### PR TITLE
STM32U5: Add ADC drivers

### PR DESCRIPTION
**Pull request by klownfish**
This pull request adds ADC drivers for the U5 series with both blocking and async reads. One quirk of the U5 series is that some models have two simultaneous revisions of the peripheral. To handle this I've had to touch the internals a bit. The [issue](https://github.com/embassy-rs/stm32-data/pull/525) in stm32-data has some more details. 

Closes issue:
https://github.com/embassy-rs/embassy/issues/3654

### CODE REVIEW

**Comment by Sandvoxel** [comment]
I just wanted to add that I’m also looking for ADC driver support for the STM32U5, as I plan to use the ADC in an upcoming project. Thanks for the work on this PR so far, and I’m looking forward to seeing it reviewed!

**Comment by Dirbaio** [comment]
could you fix CI?

**Comment by klownfish** [comment]
Should be fixed now! My first attempt failed so I did a force push to remove it from the history. I'm not entirely sure what's considered good practice with git but I hope it's okay.

**Review by Dirbaio — APPROVED** [review]
thanks!

**Pull request merged**
