### PR TITLE
Add example for bdma

### PR DESCRIPTION
**Pull request by PegasisForever**
Tested on h723zg

### CODE REVIEW

**Review by jamesmunns — COMMENTED** [review]
Just noting that this example is a little unsound, wrt uninitialized linker sections.

I think we should still merge it for now, but making a note so I can open an issue to fix it later to give a better sound example.

**Review by Dirbaio — APPROVED** [review]
thanks!

**Comment by bsodmike** [comment]
> Just noting that this example is a little unsound, wrt uninitialized linker sections.

Hi @jamesmunns I'm curious as to what you mean by "uninitlalized" - `static mut RAM_D3: [u8; 64 * 1024] = [0u8; 64 * 1024];` the RAM area here are initialised to `0u8`??

Also - more a general question, do we need to do the same with the linked area for DMA (not BDMA)?

@PegasisForever do you have any working DMA examples for I2c etc? I'm testing on the h747.

Thanks!

**Comment by bsodmike** [comment]
It also looks like we don't have an I2c BDMA transfer, I'm not sure if it's really needed?

**Comment by jamesmunns** [comment]
@bsodmike 

> Hi @jamesmunns I'm curious as to what you mean by "uninitlalized" - static mut RAM_D3: [u8; 64 * 1024] = [0u8; 64 * 1024]; the RAM area here are initialised to 0u8??

cortex-m-rt only initializes some sections in RAM, the rust compiler has no idea what the linker does, and if you place something outside of the normal regions (`.bss`, initialized to zeros; or `.data`, initialized from flash values), then the data is not initialized to what the compiler thinks it is. To fix this, you must either tell Rust that it is uninitialized, e.g. with MaybeUninit, or initialize it somehow before any Rust code runs (this includes pre_init, it's generally only possible in custom assembly or with a bootloader).

**Pull request merged**
