### PR TITLE
stm32: fdcan: try_write() and try_read() on BufferedCan impl

### PR DESCRIPTION
**Pull request by tcbennun**
Not sure that this makes sense for the non-buffered FDCAN driver, but for buffered, it's nice to have instantaneous `try` variants.

### CODE REVIEW

**Comment by tcbennun** [comment]
@Dirbaio would you mind checking why the test check is failing? thank you

**Comment by Dirbaio** [comment]
rebase on lastest git main should fix it

**Comment by cschuhen** [comment]
@tcbennun, No worries... I'm OK with this. However, I didn't bother because you can also do it from the Sender i.e. .writer().try_write(...) or Receiver

**Comment by tcbennun** [comment]
> @tcbennun, No worries... I'm OK with this. However, I didn't bother because you can also do it from the Sender i.e. .writer().try_write(...) or Receiver

Okay yeah, I missed that, I'll close to avoid bloat!

**Pull request closed without merging**
