### PR TITLE
blinking red and green leds

### PR DESCRIPTION
**Pull request by ecruzolivera**
in the example the work pins are used, this PR just makes both leds blink

### CODE REVIEW

**Comment by ecruzolivera** [comment]
I dont understand the CI/build error:

```
+ git clone -n https://github.com/ecruzolivera/embassy.git code
Cloning into 'code'...
error: 6695 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
run failed: exited with code 128
```

**Comment by Dirbaio** [comment]
bender run

**Comment by ecruzolivera** [comment]
> This will likely break blinky for someone else, it depends on which board you are using.

I agree, but I was thinking the only official ST board for the stm32f429I was the [STM32F429I-DISCO](https://www.st.com/en/evaluation-tools/32f429idiscovery.htm), and the PR PINs are for that board's leds.

Is there a recommended way of adding an example per board?

**Comment by Dirbaio** [comment]
ST also has the nucleo-stm32f429zi, the PB7 pin is the blue LED on that one.

In general we don't aim for examples to work out of the box on every single possible board, there's way too many boards. It's expected that users have to do some customization changing the chip name and pin numbers for their board.

**Pull request closed without merging**
