### PR TITLE
add convert_to_celsius function in the adc module

### PR DESCRIPTION
**Pull request by overheat**
modify RP2040 adc example to get inside biased bipolar diode voltage,
    then convert this temperature sensor data into Celsius degree,
    according to chapter 4.9.5. Temperature Sensor in RP2040 datasheet.

### CODE REVIEW

**Comment by overheat** [comment]
#1117

**Review by lulf — APPROVED** [review]
Thanks!

bors r+

**Comment by kalkyl** [comment]
Looks like CI fails because you need to run `cargo fmt` for your info...

**Comment by overheat** [comment]
Sure.

**Pull request merged**
