### PR TITLE
rp2040: add {tx,rx}-only constructors to UART

### PR DESCRIPTION
**Pull request by pferreir**
As discussed with @henrik-alser on Matrix. I also added an example, feel free to remove it if it's too much.

### CODE REVIEW

**Comment by Dirbaio** [comment]
For buffereduart, this is already available as `BufferedUart{RT}x::new()`. I don't think we should have 2 different constructors to do the same thing.

They're missing for the non-buffered uart indeed. Could you change them to `Uart{RT}x::new(), like the existing BufferedUart ones?

**Comment by pferreir** [comment]
> They're missing for the non-buffered uart indeed. Could you change them to `Uart{RT}x::new(), like the existing BufferedUart ones?

Right. I was following @henrik-alser's idea of `.new_{t,r}xonly methods`, but if you guys think it's better that way, no problem.

**Comment by pferreir** [comment]
PR Updated.

**Review by Dirbaio — APPROVED** [review]
Thanks!

for context: the `_txonly/_rxonly` naming was from before we had `split()`, so the `UartRx/UartTx` structs didn't exist. Now that they do, it's cleaner to put the constructors there since that's what you're creating in the end.

bors r+

**Comment by pferreir** [comment]
Perfect. Thanks for reviewing this so quickly!

**Pull request merged**
