### PR TITLE
*WIP* Create a device independent buffered uarte

### PR DESCRIPTION
**Pull request by lulf**
Use existing BufferedUarte for nRF to create a generic BufferedUart that
can be used for other platforms that implement traits for operating a
uart in an interrupt driven way.

Add wrapper types that can be used to split TX and RX to operate
independently, and add a split() method to the nRF implementation that
uses these wrapper types

@Dirbaio I haven't really vetted this for soundness, I'm just looking for initial comments on the approach I'm taking. Could also be this need further modifications to work with stm32, but the goal is to implement the same TimerPeripheral and UartPeripheral traits for stm32 serial.

### CODE REVIEW

**Comment by Dirbaio** [comment]
Very interesting! This would be very nice to have. The ringbuffer/irq logic is quite complex, so sharing it across all hardware would be best. I'm somewhat worried that it won't share smoothly though, since the hardware out there can be very different, but we can try! :) 

One such difference is the timer: The device-independent part should probably have nothing about timers. The timer on nrf is a "trick" to emulate "stop on idle" because the hardware doesn't support that, but other chips might not need it. For example stm32's uart does have an "idle" interrupt. Implementing "stop on idle" could be the responsibility of the UartPeripheral impl instead, letting each hardware-specific implementation do it the best way it can.

DMA also works a bit differently on stm32 (there's the uart irq and the "dma done" irq), hopefully we don't run into any blockers with that...

I think this is a great idea, but ideally it should be proven with impls for 2 different chips (likely nrf and stm32) before merging, otherwise it's very likely the abstraction won't be quite right and we'll have to refactor later.

**Comment by lulf** [comment]
> Very interesting! This would be very nice to have. The ringbuffer/irq logic is quite complex, so sharing it across all hardware would be best. I'm somewhat worried that it won't share smoothly though, since the hardware out there can be very different, but we can try! :)
> 
> One such difference is the timer: The device-independent part should probably have nothing about timers. The timer on nrf is a "trick" to emulate "stop on idle" because the hardware doesn't support that, but other chips might not need it. For example stm32's uart does have an "idle" interrupt. Implementing "stop on idle" could be the responsibility of the UartPeripheral impl instead, letting each hardware-specific implementation do it the best way it can.

Thats a good idea, thanks! It should simplify things a bit.

> 
> DMA also works a bit differently on stm32 (there's the uart irq and the "dma done" irq), hopefully we don't run into any blockers with that...
> 

I also noticed there are separate TX and RX interrupts, which might also require some changes I think.

> I think this is a great idea, but ideally it should be proven with impls for 2 different chips (likely nrf and stm32) before merging, otherwise it's very likely the abstraction won't be quite right and we'll have to refactor later.

Agreed, I'll make some of the cleanup first, then next goal is to see if I can an stm32 board to work with this.

**Comment by Dirbaio** [comment]
New info: with STM32 DMA it's possible to query how many bytes have been received *without stopping DMA*. This means DMA can be kept receiving constantly, and only needs restarting when buffer is actually filled.

So the "wait for idle and restart the RX to flush" is a nrf-specific limitation.

I'm not sure how this impacts the device-independent trait :sweat_smile:, but it certainly does look like something we should take advantage of.

**Comment by lulf** [comment]
> New info: with STM32 DMA it's possible to query how many bytes have been received _without stopping DMA_. This means DMA can be kept receiving constantly, and only needs restarting when buffer is actually filled.
> 
> So the "wait for idle and restart the RX to flush" is a nrf-specific limitation.
> 
> I'm not sure how this impacts the device-independent trait 😅, but it certainly does look like something we should take advantage of.

My take on this is after seeing the differences between nRF and STM32 and the way one would go about
doing DMA, I'm not sure how much there is to gain from having a generic BufferedUart, and that the
maintenance burden be less when having two independent implementations of the AsyncWrite +
AsyncBufRead traits.

Maybe the RingBuffer + Waker logic can be abstracted into some helper type that could be shared, but
I think it will be easier to do that once having proper implementations for both nRF and STM32 to
see the common patterns.  Given that the architectures don't seem to change dramatically, I think
the maintenance burden of having two separate implementations will still be low.

I think what would be more valuable is to be able to optionally split TX and RX into separate types,
which makes it easier to work with for UART-based modems IMO.

Wdyt?

**Comment by Dirbaio** [comment]
:+1: to waiting to have one for stm32 and reconsidering later

:+1:  to adding split to Uarte/BufferedUarte. I've missed that when messing with modems too.

**Pull request closed without merging**
