### PR TITLE
Add support for the stm32 LTDC display peripheral

### PR DESCRIPTION
**Pull request by ninjasource**
This PR adds support for the LTDC display peripheral typically found on high-end graphics oriented stm32 mcus. The included example demonstrates high frame-rate animation on an stm32h735g-dk whilst running another blinky embassy task. The implementation was inspired by how the LTDC is used in the stm32h7xx-hal so if anyone spots any glaring stm32h7-only stuff please let me know. I decided not to use the standardized `embedded_display_controller` library because it was too "blocking focused". Therefore, at the cost of duplicating a few small graphics primitives, this implementation is standalone.

NOTE: The PR requires a small change to the `stm32-data` library for which there is an open [PR](https://github.com/embassy-rs/stm32-data/pull/496). Once this is in the `stm32-metapac` dependencies on `embassy-stm32` should be updated. For convenience, I have linked a pre-built metapac as a temporary measure.

### CODE REVIEW

**Comment by joelsa** [comment]
This breaks the DSI example at https://github.com/embassy-rs/embassy/blob/main/examples/stm32f469/src/bin/dsi_bsp.rs, can you update the example to reflect the changes made?

I can then run it on the Nucleo-F469 to see if it works.

**Comment by ninjasource** [comment]
> This breaks the DSI example at https://github.com/embassy-rs/embassy/blob/main/examples/stm32f469/src/bin/dsi_bsp.rs, can you update the example to reflect the changes made?
> 
> I can then run it on the Nucleo-F469 to see if it works.

Hi, yes, please do, thanks. I have fixed the compilation error with the dsi_bsp and I am trying to figure out how to do the RCC stuff with the appropriate feature flags so there are still CI issues I need to solve.

**Review by Dirbaio — APPROVED** [review]
thank you!

**Comment by ninjasource** [comment]
Woot woot, my first embassy contribution. This is such an awesome repository, I am truly honored! Thanks Dario.

**Pull request merged**
