### PR TITLE
Add FDCAN Buffered mode.

### PR DESCRIPTION
**Pull request by cschuhen**
Clean up and prep for buffered IRQ mode.
    - Reduce code duplicaiton in read/write methods
    - General clean-up
    - Prepare for buffered mode
Add Buffered mode

This branch builds on: https://github.com/embassy-rs/embassy/pull/2571
as well as the already merged: https://github.com/embassy-rs/embassy/pull/2475

### CODE REVIEW

**Comment by cschuhen** [comment]
Apologies if it's rude to open a new PR when the dependent is still being considered. This PR has been my goal all along and is what I have been working towards as far as the API is concerned. I considered it mandatory to have configurable-length IRQ(or DMA) driven buffering. Especially on the read side, this is pretty necessary for many applications.

**Comment by cschuhen** [comment]
I also feel that fdcan.rs is quite large. I experimented and realised that I could break out a lot of what is in there that the user does not touch into another file (fd/internals.rs I used). I didn't include that work because it felt it hard to review the diffs. I figure after merging this it would be better to just do that as a pure *move stuff about* PR. Thoughts?

**Comment by cschuhen** [comment]
@Dirbaio, could you add trusted flag please.

**Comment by cschuhen** [comment]
@Dirbaio, @tcbennun, @blaa, I pushed another changeset to this PR.
I really did find the operating mode typestates frustrating. Then I remembered that Dario mentioned eliminating them in the comments of https://github.com/embassy-rs/embassy/pull/2475 . So I have gotten rid of them. Now we just have 2 modes, one for configuration and one for operating? Does this seem OK to you all?

I could probably also add a shortcut mode to skip needing the configurator object completely with limited functionality i.e. filters etc. 
Or perhaps it is better to remove the Configurator totally and try to specify everything from the config struct? However that might be less ideal for things like setting filters etc.

**Comment by lulf** [comment]
bender run

**Comment by cschuhen** [comment]
> bender run

Guess not... I noticed that manually trying to do teleprobe tests on the HIL farm isn't working either.

**Comment by Dirbaio** [comment]
bender run

it's back up now

**Comment by cschuhen** [comment]
Thanks, it's passing now.

**Comment by cschuhen** [comment]
@JomerDev FYI.

**Comment by Dirbaio** [comment]
@cschuhen LGTM modulo the comments in https://github.com/embassy-rs/embassy/pull/2571#issuecomment-1960389798

do you want to merge the two open PRs and fix these in a follow-up PR, so you don't have to worry about rebasing?

**Comment by cschuhen** [comment]
That would be ideal. Actually, can't we just merge this one? It should be a superset(the first 3 changesets of this == the other PR). superset. Then can we "close without merging" on the other one? 

I didn't set out to confuse things with 2 PR's. But after opening the first, I continued on and didn't want to confuse the first just in case you were half way through reviewing it.

**Comment by Dirbaio** [comment]
:fire:

**Comment by cschuhen** [comment]
Looks like all of the FDCAN tests passed. HIL farm issues?

**Comment by cschuhen** [comment]
Great! Thanks for your time. I'll get onto the follow-up fixes soon.

**Comment by Dirbaio** [comment]
yeah, unrelated issues so I force-merged this.

**Pull request merged**
