### PR TITLE
stm32: Make initialization of I2C and USART consistent with SPI

### PR DESCRIPTION
**Pull request by honzasp**
This PR contains a bunch of small improvements related to driver initialization:

- Use `new_pin!` in I2C and buffered USART.
- Disconnect pins of I2C and USART on drop.
- Move initialization code into function that's not generic in `T`: I found that this slightly decreases code size.

Marked as draft because this PR builds on #3002.

### CODE REVIEW

**Review by Dirbaio — APPROVED** [review]
thanks!

**Comment by honzasp** [comment]
Seems like the CI got stuck, perhaps this will help?

bender run

**Comment by Dirbaio** [comment]
bender run

**Comment by honzasp** [comment]
I rebased the branch because of merge conflicts.

**Review by Dirbaio — APPROVED** [review]
thanks!

**Comment by Dirbaio** [comment]
seems this makes some UART tests fail. I've added the `trusted` label so HIL tests run from now on when you push.

**Comment by Dirbaio** [comment]
bender run

**Comment by Dirbaio** [comment]
bender run

**Pull request merged**
