### PR TITLE
Add OTG_HS support for STM32H7R/S

### PR DESCRIPTION
**Pull request by doesnotcompete**
This adds support for the embedded high-speed USB peripheral on the STM32H7R/S series. I've confirmed the `usb_serial` example works on a Nucleo-H7S3 board using the internal HS PHY.
These changes build on prior work by @RileyLeff in #3289.

There are some remaining issues:
- I haven't tested this with the OTG_FS peripheral or on other boards with different clock configurations.
- I'm not sure the way I've implemented the clock configuration is ideal. The USBPHYC on the H7R/S series embeds a PLL that can receive a range of different frequencies via the `USBPHYCSEL` clock mux and generates the necessary 48 and 60MHz clocks for the OTG blocks internally (see the clock diagram below). I've simply added `USBPHYC` as a fallback clock for the `OTG_HS` peripheral in [`stm32-data`](https://github.com/embassy-rs/stm32-data/blob/acaf04256034066bd5b3a8426224ccf3e4cb7d19/stm32-data-gen/src/rcc.rs#L308) to get the clock generator to generate a mux definition and then explicitly pick the corresponding reference clock in the H-series RCC driver, but this approach results in the PLL input frequency being registered as the actual OTG kernel clock.
- Possibly related to this, `ahb_freq` in `otg.rs` doesn't represent the AHB bus frequency, but just this USBPHYC PLL input frequency. I've just skipped the check of a sufficient AHB clock on the H7R/S, as I didn't find a straight-forward solution and the USBPHYC PLL input might very well be below 30MHz, but this is likely not ideal.

usb_clk

### CODE REVIEW

**Comment by doesnotcompete** [comment]
The CI failure is apparently caused by a missing definition of the `OTG_HS` IP block in the `cubedb` source files of `stm32-data`.
`STM32H7R7A8Ix.xml` and `STM32H7S7Z8Jx.xml` only include the block for `USB_OTG_FS`, although all H7R/S MCUs, including the [H7R7A8](https://www.st.com/en/microcontrollers-microprocessors/stm32h7r7a8.html) and [H7S7Z8](https://www.st.com/en/microcontrollers-microprocessors/stm32h7s7z8.html), should have HS USB with an integrated PHY.
I'm not sure what'd be the best way to fix this.

**Comment by RileyLeff** [comment]
really appreciate your continued work on this! i'm pretty out of my depth here, would not have figured this out myself.

**Comment by Dirbaio** [comment]
> The CI failure is apparently caused by a missing definition of the OTG_HS IP block in the cubedb source files of stm32-data.
STM32H7R7A8Ix.xml and STM32H7S7Z8Jx.xml only include the block for USB_OTG_FS, although all H7R/S MCUs, including the [H7R7A8](https://www.st.com/en/microcontrollers-microprocessors/stm32h7r7a8.html) and [H7S7Z8](https://www.st.com/en/microcontrollers-microprocessors/stm32h7s7z8.html), should have HS USB with an integrated PHY.

wow that's annoying. I've tried updating the xmls from the latest Cube but OTG_HS is still missing. I'd just workaround it for now:  use `#[cfg(peri_otg_hs)]` to conditionally-compile code only if OTG_HS is present.

I'd wait for ST to fix it, perhaps report it. Where do you report cubemx bugs? :thinking:

**Comment by doesnotcompete** [comment]
> > The CI failure is apparently caused by a missing definition of the OTG_HS IP block in the cubedb source files of stm32-data.
> > STM32H7R7A8Ix.xml and STM32H7S7Z8Jx.xml only include the block for USB_OTG_FS, although all H7R/S MCUs, including the [H7R7A8](https://www.st.com/en/microcontrollers-microprocessors/stm32h7r7a8.html) and [H7S7Z8](https://www.st.com/en/microcontrollers-microprocessors/stm32h7s7z8.html), should have HS USB with an integrated PHY.
> 
> wow that's annoying. I've tried updating the xmls from the latest Cube but OTG_HS is still missing. I'd just workaround it for now: use `#[cfg(peri_otg_hs)]` to conditionally-compile code only if OTG_HS is present.
> 
> I'd wait for ST to fix it, perhaps report it. Where do you report cubemx bugs? 🤔

That's a great idea :) I've added a check in the latest commit and also tried reporting the issue to ST here on GitHub.

**Review by Dirbaio — APPROVED** [review]
thanks! :rocket:

**Pull request merged**
