### PR TITLE
Gpio dynamic flex

### PR DESCRIPTION
**Pull request by AntoineMugnier**
Add Flex GPIO type for embassy-stm32 as it is the case for  embassy-nrf.

### CODE REVIEW

**Comment by Dirbaio** [comment]
Could you rustfmt it so that CI is happy?

**Review by Dirbaio — APPROVED** [review]
Really nice work, thanks for your contribution! :)

bors r+

**Comment by AntoineMugnier** [comment]
> Really nice work, thanks for your contribution! :)
> 
> bors r+

Thank you,  it's my pleasure 😃

**Comment by nviennot** [comment]
Awesome! 👍

**Pull request merged**
