### PR TITLE
net-esp-hosted: update payload header interface type defines

### PR DESCRIPTION
**Pull request by andelf**
- Update the `PayloadHeader` interface type defines
- Compatible with current master https://github.com/espressif/esp-hosted/commit/ce3c50a33fa4bc562a1b6cbcee292c1ae0b0a404
  - See-also https://github.com/espressif/esp-hosted/blob/ce3c50a33fa4bc562a1b6cbcee292c1ae0b0a404/esp_hosted_fg/common/include/adapter.h#L42-L51
  
Tested with the following code with RPi Pico(RP2040) + ESP32-C6, default wiring:

```rust
#![no_std]
#![no_main]
#![feature(type_alias_impl_trait)]

extern crate alloc;

use core::mem::MaybeUninit;

use alloc::boxed::Box;
use defmt::{info, unwrap, warn};
use embassy_executor::Spawner;
use embassy_net::{tcp::TcpSocket, Stack, StackResources};
use embassy_net_esp_hosted as hosted;
use embassy_rp::{
    gpio::{AnyPin, Input, Level, Output, Pin, Pull},
    peripherals,
    spi::{self, Spi},
};
use embassy_time::{Delay, Duration};
use embedded_hal_bus::spi::ExclusiveDevice;
use embedded_io_async::Write;
use hosted::State;
use {defmt_rtt as _, panic_probe as _};

use embedded_alloc::Heap;

#[global_allocator]
static HEAP: Heap = Heap::empty();

// NOTE: Net Stack is big, need to fit it.
const HEAP_SIZE: usize = 1024 * 20;
static mut HEAP_MEM: [MaybeUninit<u8>; HEAP_SIZE] = [MaybeUninit::uninit(); HEAP_SIZE];

const WIFI_NETWORK: &str = "Embassy";
const WIFI_PASSWORD: &str = "A-strong-password";

#[embassy_executor::task]
async fn wifi_task(
    runner: hosted::Runner<
        'static,
        ExclusiveDevice<
            Spi<'static, peripherals::SPI0, spi::Async>,
            Output<'static, AnyPin>,
            Delay,
        >,
        Input<'static, AnyPin>,
        Output<'static, AnyPin>,
    >,
) -> ! {
    runner.run().await
}

#[embassy_executor::task]
async fn net_task(stack: &'static Stack<hosted::NetDriver<'static>>) -> ! {
    stack.run().await
}

#[embassy_executor::main]
async fn main(spawner: Spawner) {
    {
        unsafe { HEAP.init(HEAP_MEM.as_ptr() as usize, HEAP_SIZE) }
    }

    let p = embassy_rp::init(Default::default());
    let mut led = Output::new(p.PIN_25, Level::Low);

    /*
    ESP32 Pin	ESP32-S2/S3	ESP32-C2/C3/C6	Function
    IO19	    IO13	IO2	    MISO
    IO23	    IO11	IO7	    MOSI
    IO18	    IO12	IO6	    CLK
    IO5	        IO10	IO10	CS
    IO2	        IO2	    IO3	    Handshake
    IO4	        IO4	    IO4	    Data Ready from ESP
    EN	        RST	    RST	    Reset ESP
    GND	        GND	    GND	    GND
    */

    info!("Hello world");
    let clk = p.PIN_2;
    let mosi = p.PIN_3;
    let miso = p.PIN_4;
    let cs = Output::new(p.PIN_5.degrade(), Level::High);
    let handshake = Input::new(p.PIN_6.degrade(), Pull::Up);
    let ready = Input::new(p.PIN_7.degrade(), Pull::None);
    let reset = Output::new(p.PIN_8.degrade(), Level::Low);

    let mut config = spi::Config::default();
    config.frequency = 10_000_000;
    config.phase = spi::Phase::CaptureOnSecondTransition;
    config.polarity = spi::Polarity::IdleLow;
    let spi = Spi::new(p.SPI0, clk, mosi, miso, p.DMA_CH0, p.DMA_CH1, config);
    let spi: ExclusiveDevice<Spi<'_, peripherals::SPI0, spi::Async>, Output<'_, AnyPin>, Delay> =
        ExclusiveDevice::new(spi, cs, Delay);

    let state = Box::new(State::new());

    let (device, mut control, runner) =
        embassy_net_esp_hosted::new(Box::leak(state), spi, handshake, ready, reset).await;

    unwrap!(spawner.spawn(wifi_task(runner)));
    unwrap!(control.init().await);

    unwrap!(control.connect(WIFI_NETWORK, WIFI_PASSWORD).await);

    info!("connected!");
    let config = embassy_net::Config::dhcpv4(Default::default());

    let stack = Box::leak(Box::new(Stack::new(
        device,
        config,
        Box::leak(Box::new(StackResources::<2>::new())),
        0xefefcafe,
    )));

    unwrap!(spawner.spawn(net_task(stack)));

    // And now we can use it!

    let mut rx_buffer = [0; 4096];
    let mut tx_buffer = [0; 4096];
    let mut buf = [0; 4096];

    loop {
        let mut socket = TcpSocket::new(stack, &mut rx_buffer, &mut tx_buffer);
        socket.set_timeout(Some(embassy_time::Duration::from_secs(10)));
        socket.set_keep_alive(Some(Duration::from_secs(5)));

        info!("Listening on 23/tcp...");
        if let Err(e) = socket.accept(23).await {
            warn!("accept error: {:?}", e);
            continue;
        }

        info!("Received connection from {:?}", socket.remote_endpoint());

        socket
            .write_all(b"Hello from embassy-net + RP2040 + esp-hosted(ESP32C6)!\r\n")
            .await
            .unwrap();

        loop {
            led.toggle();
            let n = match socket.read(&mut buf).await {
                Ok(0) => {
                    warn!("read EOF");
                    break;
                }
                Ok(n) => n,
                Err(e) => {
                    warn!("read error: {:?}", e);
                    break;
                }
            };

            info!("rxd {:02x}", &buf[..n]);

            match socket.write_all(&buf[..n]).await {
                Ok(()) => {}
                Err(e) => {
                    warn!("write error: {:?}", e);
                    break;
                }
            };
        }
    }
}
```

### CODE REVIEW

**Comment by Dirbaio** [comment]
Did they really do a breaking change to the SPI protocol? :sob:  Commit that did the change seems to be https://github.com/espressif/esp-hosted/commit/04ac48b2b8548a674018f5ea74e58d90a3ce0f1c ... 

The firmware currently supported by `embassy-net-esp-hosted` is the latest released one, https://github.com/espressif/esp-hosted/releases/tag/release%2Ffg-v0.0.5 . If we do this change then it'll start working with newer firmwares, but stop working with older firmwares. This is a problem for people who have devices in the wild with older firmwares (like me :sweat_smile:). I'm not sure what we should do.

**Comment by andelf** [comment]
🥲I'll check how to get it compatible with both.
How about firing an issue on esp-hosted, before the final release?

**Comment by Dirbaio** [comment]
I don't think getting it compatible with both at runtime will be easy :S
Perhaps we can add Cargo features.

it'd be good to get clarification from Espressif whether the breaking change is intended, yes.

**Comment by andelf** [comment]
I hope https://github.com/espressif/esp-hosted/issues/297 can be resolved before its next release.

A possible workaround is to check the type code of the first incoming packet against either 4 or 5.

**Comment by andelf** [comment]
Close as upstream issue https://github.com/espressif/esp-hosted/issues/297 is finally resolved in https://github.com/espressif/esp-hosted/commit/fabe8725d296ed168a5b9c86cad7a7357a5f0915 .

**Pull request closed without merging**
