### PR TITLE
cyw43: write a bluetooth firmware reader/writer

### PR DESCRIPTION
**Pull request by brandonros**
@Dirbaio this doesn't actually work (BT_CTRL_REG_ADDR gives 0xF4 on first read and then 0x00 on all other reads and never matches BT_READY bitmask requirement) and I don't know why, any tips on debugging? again the question of "are we writing firmware at the right time" comes into mind

I could also be missing some very specific backplane/interrupt registers/masks or something?

part of https://github.com/embassy-rs/embassy/issues/1516

### CODE REVIEW

**Comment by Dirbaio** [comment]
> any tips on debugging?

unfortunately no... this stuff is always "poke at it blindly until it comes alive"  :smiling_face_with_tear:

**Comment by brandonros** [comment]
image

https://www.infineon.com/dgdl/Infineon-CYW43439-DataSheet-v05_00-EN.pdf?fileId=8ac78c8c8929aa4d01893ee30e391f7a&redirId=260879

Do we need to do this pin thingie?

**Comment by Dirbaio** [comment]
accordign to the [pico w datahseet](https://datasheets.raspberrypi.com/picow/pico-w-datasheet.pdf) schematic (appendix B) they're both wired together, so I don't think it's that :(

**Comment by brandonros** [comment]
@Dirbaio I think I found something.

https://github.com/georgerobotics/cyw43-driver/blob/main/firmware/wb43439A0_7_95_49_00_combined.h

I missed that Bluetooth uses a different firmware (not found anywhere here https://github.com/Infineon/wifi-host-driver/tree/master/WiFi_Host_Driver/resources/firmware/COMPONENT_43439 where we usually get firmware)

The string inside it is `Version: 7.95.61 (abcd531 CY)`

What I could use your help on, I have DEFMT_LOG set to `trace` now and this `firmware-logs` feature on: `cyw43 = { path = "../../embassy/cyw43", features = ["defmt", "firmware-logs"] }`

Do I need to SWD probe and then `probe-rs` this firmware in? I would have thought `cyw43::new(state, pwr, spi, firmware, Some(bluetooth_firmware)).await;` flashes it to `0x10100000` at init/runtime but I see we are writing it to `CHIP.atcm_ram_base_address` which is `0`

I only ask because what I get back on `firmware-logs` does not match the version I'm trying to upload to it: 

```
└─ cyw43_pio::{impl#0}::cmd_read::{async_fn#0} @ /Users/brandon/Desktop/embassy/cyw43-pio/src/lib.rs:180
5.615449 DEBUG LOGS: 000000.001 
└─ cyw43::runner::{impl#1}::log_read::{async_fn#0} @ /Users/brandon/Desktop/embassy/cyw43/src/fmt.rs:127
5.617404 DEBUG LOGS: RTE (SDIO-CDC) 7.95.60 (abcd531 CY) on BCM43439 r5 @ 37.4/81.6/81.6MHz
└─ cyw43::runner::{impl#1}::log_read::{async_fn#0} @ /Users/brandon/Desktop/embassy/cyw43/src/fmt.rs:127
5.624396 DEBUG LOGS: 000000.004 sdpcmdcdc0: Broadcom SDPCMD CDC driver
└─ cyw43::runner::{impl#1}::log_read::{async_fn#0} @ /Users/brandon/Desktop/embassy/cyw43/src/fmt.rs:127
5.656985 DEBUG LOGS: 000000.054 wl0: Broadcom BCM43439 802.11 Wireless Controller 7.95.60 (abcd531 CY)
└─ cyw43::runner::{impl#1}::log_read::{async_fn#0} @ /Users/brandon/Desktop/embassy/cyw43/src/fmt.rs:127
5.664920 DEBUG LOGS: 000000.056 TCAM: 256 used: 77 exceed:0
└─ cyw43::runner::{impl#1}::log_read::{async_fn#0} @ /Users/brandon/Desktop/embassy/cyw43/src/fmt.rs:127
```

Which makes me think I don't really understand this flashing process well.

```rust
    let firmware = include_bytes!("../../../embassy/cyw43-firmware/wb43439A0_7_95_49_00.bin");
    let clm = include_bytes!("../../../embassy/cyw43-firmware/wb43439A0_7_95_49_00_clm.bin");
    let bluetooth_firmware = include_bytes!("../../../embassy/cyw43-firmware/cyw43_btfw_43439.bin");
    // cyw43 init
    let pwr = Output::new(p.PIN_23, Level::Low);
    let cs = Output::new(p.PIN_25, Level::High);
    let mut pio = Pio::new(p.PIO0, Irqs);
    let spi = PioSpi::new(
        &mut pio.common,
        pio.sm0,
        pio.irq0,
        cs,
        p.PIN_24,
        p.PIN_29,
        p.DMA_CH0,
    );
    let state = make_static!(cyw43::State::new());
    let (_net_device, mut control, runner) = cyw43::new(state, pwr, spi, firmware, Some(bluetooth_firmware)).await;
```

**Comment by brandonros** [comment]
Do we see on any datasheet anywhere what `BT_CTRL_REG_ADDR = 000000f4` might represent? 

`pub(crate) const BT_CTRL_REG_ADDR: u32 = 0x18000c7c;`

**Comment by brandonros** [comment]
The problem I'm running into (I think) is that the C SDK + driver (which work fine) look like this when blending the RAM + Bluetooth firmware together:

```
cybt_fw_download ori_fwmem_start_addr = 1921e000 cybt_mem_read(ROUNDDN(fwmem_end_addr, 4) = 1921e040 fwmem_end_data = 407c00c3
cybt_fw_download ori_fwmem_start_addr = 1921f000 cybt_mem_read(ROUNDDN(fwmem_end_addr, 4) = 1921f0f8 fwmem_end_data = 3a42ef81
cybt_fw_download ori_fwmem_start_addr = 1921f0fb cybt_mem_read(fwmem_start_addr = 1921f0f8 fwmem_start_data = 01280481
cybt_fw_download ori_fwmem_start_addr = 1921f0fb cybt_mem_read(ROUNDDN(fwmem_end_addr, 4) = 1921f1f4 fwmem_end_data = 58927c48
cybt_fw_download ori_fwmem_start_addr = 1921f1f6 cybt_mem_read(fwmem_start_addr = 1921f1f4 fwmem_start_data = ca067c48
cybt_fw_download ori_fwmem_start_addr = 1921f1f6 cybt_mem_read(ROUNDDN(fwmem_end_addr, 4) = 1921f2f0 fwmem_end_data = 20ee373c
cybt_fw_download ori_fwmem_start_addr = 1921f2f1 cybt_mem_read(fwmem_start_addr = 1921f2f0 fwmem_start_data = ffee373c
cybt_fw_download ori_fwmem_start_addr = 1921f3ec cybt_mem_read(ROUNDDN(fwmem_end_addr, 4) = 1921f4e4 fwmem_end_data = cc40d83f
cybt_fw_download ori_fwmem_start_addr = 1921f4e7 cybt_mem_read(fwmem_start_addr = 1921f4e4 fwmem_start_data = 06ff453f
cybt_fw_download ori_fwmem_start_addr = 1921f4e7 cybt_mem_read(ROUNDDN(fwmem_end_addr, 4) = 1921f5e0 fwmem_end_data = 9b3c6bc1
cybt_fw_download ori_fwmem_start_addr = 1921f5e2 cybt_mem_read(fwmem_start_addr = 1921f5e0 fwmem_start_data = 60006bc1
cybt_fw_download ori_fwmem_start_addr = 1921f5e2 cybt_mem_read(ROUNDDN(fwmem_end_addr, 4) = 1921f6dc fwmem_end_data = cb937959
cybt_fw_download ori_fwmem_start_addr = 1921f6dd cybt_mem_read(fwmem_start_addr = 1921f6dc fwmem_start_data = 13937959
cybt_fw_download ori_fwmem_start_addr = 1921f7d8 cybt_mem_read(ROUNDDN(fwmem_end_addr, 4) = 1921f8d0 fwmem_end_data = ad0a1802
cybt_fw_download ori_fwmem_start_addr = 1921f8d3 cybt_mem_read(fwmem_start_addr = 1921f8d0 fwmem_start_data = 70bd9802
cybt_fw_download ori_fwmem_start_addr = 1921f8d3 cybt_mem_read(ROUNDDN(fwmem_end_addr, 4) = 1921f9cc fwmem_end_data = 0f2230be
cybt_fw_download ori_fwmem_start_addr = 1921f9ce cybt_mem_read(fwmem_start_addr = 1921f9cc fwmem_start_data = 9f1230be
cybt_fw_download ori_fwmem_start_addr = 1921f9ce cybt_mem_read(ROUNDDN(fwmem_end_addr, 4) = 1921fac8 fwmem_end_data = 945a6003
cybt_fw_download ori_fwmem_start_addr = 1921fac9 cybt_mem_read(fwmem_start_addr = 1921fac8 fwmem_start_data = e05a6003
cybt_fw_download ori_fwmem_start_addr = 1921fbc4 cybt_mem_read(ROUNDDN(fwmem_end_addr, 4) = 1921fc20 fwmem_end_data = 5de36d8f
cybt_fw_download ori_fwmem_start_addr = 190d0200 cybt_mem_read(ROUNDDN(fwmem_end_addr, 4) = 190d02f8 fwmem_end_data = 74928775
cybt_fw_download ori_fwmem_start_addr = 190d02fb cybt_mem_read(fwmem_start_addr = 190d02f8 fwmem_start_data = 40f80c75
cybt_fw_download ori_fwmem_start_addr = 190d02fb cybt_mem_read(ROUNDDN(fwmem_end_addr, 4) = 190d03f4 fwmem_end_data = 3c386f18
cybt_fw_download ori_fwmem_start_addr = 190d03f6 cybt_mem_read(fwmem_start_addr = 190d03f4 fwmem_start_data = f0fa6f18
cybt_fw_download ori_fwmem_start_addr = 190d03f6 cybt_mem_read(ROUNDDN(fwmem_end_addr, 4) = 190d04f0 fwmem_end_data = 11a134e6
cybt_fw_download ori_fwmem_start_addr = 190d04f1 cybt_mem_read(fwmem_start_addr = 190d04f0 fwmem_start_data = b2a134e6
cybt_fw_download ori_fwmem_start_addr = 190d05ec cybt_mem_read(ROUNDDN(fwmem_end_addr, 4) = 190d06e4 fwmem_end_data = e0080d97
cybt_fw_download ori_fwmem_start_addr = 190d06e7 cybt_mem_read(fwmem_start_addr = 190d06e4 fwmem_start_data = a5709897
cybt_fw_download ori_fwmem_start_addr = 190d06e7 cybt_mem_read(ROUNDDN(fwmem_end_addr, 4) = 190d07e0 fwmem_end_data = 8a559a1e
cybt_fw_download ori_fwmem_start_addr = 190d07e2 cybt_mem_read(fwmem_start_addr = 190d07e0 fwmem_start_data = 491c9a1e
cybt_fw_download ori_fwmem_start_addr = 190d07e2 cybt_mem_read(ROUNDDN(fwmem_end_addr, 4) = 190d08dc fwmem_end_data = c52d0325
cybt_fw_download ori_fwmem_start_addr = 190d08dd cybt_mem_read(fwmem_start_addr = 190d08dc fwmem_start_data = 202d0325
cybt_fw_download ori_fwmem_start_addr = 190d09d8 cybt_mem_read(ROUNDDN(fwmem_end_addr, 4) = 190d0ad0 fwmem_end_data = a27400f4
cybt_fw_download ori_fwmem_start_addr = 190d0ad3 cybt_mem_read(fwmem_start_addr = 190d0ad0 fwmem_start_data = 401cc0f4
cybt_fw_download ori_fwmem_start_addr = 190d0ad3 cybt_mem_read(ROUNDDN(fwmem_end_addr, 4) = 190d0bcc fwmem_end_data = 94aac1aa
cybt_fw_download ori_fwmem_start_addr = 190d0bce cybt_mem_read(fwmem_start_addr = 190d0bcc fwmem_start_data = 22f4c1aa
cybt_fw_download ori_fwmem_start_addr = 190d0bce cybt_mem_read(ROUNDDN(fwmem_end_addr, 4) = 190d0cc8 fwmem_end_data = 00931e1d
cybt_fw_download ori_fwmem_start_addr = 190d0cc9 cybt_mem_read(fwmem_start_addr = 190d0cc8 fwmem_start_data = 2a931e1d
```

Rust:

```
5.929732 DEBUG upload_bluetooth_firmware: pad end ori_dest_start_addr = 1921e000 bp_read(1921e040) memory_value_bytes = [b4, da, 06, 00]
5.986426 DEBUG upload_bluetooth_firmware: pad end ori_dest_start_addr = 1921f000 bp_read(1921f0f8) memory_value_bytes = [44, 7d, 00, c3]
6.051043 DEBUG upload_bluetooth_firmware: pad start ori_dest_start_addr = 1921f0fb bp_read(1921f0f8) memory_value_bytes = [32, 42, ef, 85]
6.072549 DEBUG upload_bluetooth_firmware: pad end ori_dest_start_addr = 1921f0fb bp_read(1921f1f4) memory_value_bytes = [59, 96, 04, c3]
6.142016 DEBUG upload_bluetooth_firmware: pad start ori_dest_start_addr = 1921f1f6 bp_read(1921f1f4) memory_value_bytes = [59, 96, 7c, 48]
6.168019 DEBUG upload_bluetooth_firmware: pad end ori_dest_start_addr = 1921f1f6 bp_read(1921f2f0) memory_value_bytes = [ca, 06, 04, c3]
6.247903 DEBUG upload_bluetooth_firmware: pad start ori_dest_start_addr = 1921f2f1 bp_read(1921f2f0) memory_value_bytes = [a0, ee, 35, 2c]
6.375027 DEBUG upload_bluetooth_firmware: pad end ori_dest_start_addr = 1921f3ec bp_read(1921f4e4) memory_value_bytes = [ff, 06, 04, c3]
6.457268 DEBUG upload_bluetooth_firmware: pad start ori_dest_start_addr = 1921f4e7 bp_read(1921f4e4) memory_value_bytes = [cc, 40, d8, 3f]
6.485110 DEBUG upload_bluetooth_firmware: pad end ori_dest_start_addr = 1921f4e7 bp_read(1921f5e0) memory_value_bytes = [06, ff, 45, c3]
6.567313 DEBUG upload_bluetooth_firmware: pad start ori_dest_start_addr = 1921f5e2 bp_read(1921f5e0) memory_value_bytes = [9b, 3c, 69, c1]
6.593684 DEBUG upload_bluetooth_firmware: pad end ori_dest_start_addr = 1921f5e2 bp_read(1921f6dc) memory_value_bytes = [60, 00, 45, c3]
6.670787 DEBUG upload_bluetooth_firmware: pad start ori_dest_start_addr = 1921f6dd bp_read(1921f6dc) memory_value_bytes = [cb, 93, 79, 5d]
6.780046 DEBUG upload_bluetooth_firmware: pad end ori_dest_start_addr = 1921f7d8 bp_read(1921f8d0) memory_value_bytes = [13, 00, 45, c3]
6.854105 DEBUG upload_bluetooth_firmware: pad start ori_dest_start_addr = 1921f8d3 bp_read(1921f8d0) memory_value_bytes = [ad, 08, 10, 02]
6.881361 DEBUG upload_bluetooth_firmware: pad end ori_dest_start_addr = 1921f8d3 bp_read(1921f9cc) memory_value_bytes = [70, bd, 98, c3]
6.962777 DEBUG upload_bluetooth_firmware: pad start ori_dest_start_addr = 1921f9ce bp_read(1921f9cc) memory_value_bytes = [0f, 22, 30, be]
6.989754 DEBUG upload_bluetooth_firmware: pad end ori_dest_start_addr = 1921f9ce bp_read(1921fac8) memory_value_bytes = [9f, 12, 98, c3]
7.070684 DEBUG upload_bluetooth_firmware: pad start ori_dest_start_addr = 1921fac9 bp_read(1921fac8) memory_value_bytes = [84, 5a, 60, 01]
7.181556 DEBUG upload_bluetooth_firmware: pad end ori_dest_start_addr = 1921fbc4 bp_read(1921fc20) memory_value_bytes = [e0, 12, 98, c3]
7.273635 DEBUG upload_bluetooth_firmware: pad end ori_dest_start_addr = 190d0200 bp_read(190d02f8) memory_value_bytes = [5d, e1, 6d, 8f]
7.355899 DEBUG upload_bluetooth_firmware: pad start ori_dest_start_addr = 190d02fb bp_read(190d02f8) memory_value_bytes = [64, 90, 9f, 75]
7.383152 DEBUG upload_bluetooth_firmware: pad end ori_dest_start_addr = 190d02fb bp_read(190d03f4) memory_value_bytes = [3e, 38, 0c, 8f]
7.465643 DEBUG upload_bluetooth_firmware: pad start ori_dest_start_addr = 190d03f6 bp_read(190d03f4) memory_value_bytes = [3e, 38, 2f, 1c]
7.493554 DEBUG upload_bluetooth_firmware: pad end ori_dest_start_addr = 190d03f6 bp_read(190d04f0) memory_value_bytes = [f0, fa, 0c, 8f]
7.577007 DEBUG upload_bluetooth_firmware: pad start ori_dest_start_addr = 190d04f1 bp_read(190d04f0) memory_value_bytes = [51, a1, 74, e6]
7.704294 DEBUG upload_bluetooth_firmware: pad end ori_dest_start_addr = 190d05ec bp_read(190d06e4) memory_value_bytes = [b2, fa, 0c, 8f]
7.787247 DEBUG upload_bluetooth_firmware: pad start ori_dest_start_addr = 190d06e7 bp_read(190d06e4) memory_value_bytes = [e0, 08, 0d, 87]
7.815067 DEBUG upload_bluetooth_firmware: pad end ori_dest_start_addr = 190d06e7 bp_read(190d07e0) memory_value_bytes = [a5, 70, 98, 8f]
7.898680 DEBUG upload_bluetooth_firmware: pad start ori_dest_start_addr = 190d07e2 bp_read(190d07e0) memory_value_bytes = [8a, 57, 9c, 56]
7.926582 DEBUG upload_bluetooth_firmware: pad end ori_dest_start_addr = 190d07e2 bp_read(190d08dc) memory_value_bytes = [49, 1c, 98, 8f]
8.010562 DEBUG upload_bluetooth_firmware: pad start ori_dest_start_addr = 190d08dd bp_read(190d08dc) memory_value_bytes = [c5, 65, 03, 27]
8.139461 DEBUG upload_bluetooth_firmware: pad end ori_dest_start_addr = 190d09d8 bp_read(190d0ad0) memory_value_bytes = [20, 1c, 98, 8f]
8.223209 DEBUG upload_bluetooth_firmware: pad start ori_dest_start_addr = 190d0ad3 bp_read(190d0ad0) memory_value_bytes = [a2, 70, 00, f4]
8.251048 DEBUG upload_bluetooth_firmware: pad end ori_dest_start_addr = 190d0ad3 bp_read(190d0bcc) memory_value_bytes = [40, 1c, c0, 8f]
8.334488 DEBUG upload_bluetooth_firmware: pad start ori_dest_start_addr = 190d0bce bp_read(190d0bcc) memory_value_bytes = [94, aa, c5, aa]
8.361990 DEBUG upload_bluetooth_firmware: pad end ori_dest_start_addr = 190d0bce bp_read(190d0cc8) memory_value_bytes = [22, f4, c0, 8f]
8.424141 DEBUG upload_bluetooth_firmware: pad start ori_dest_start_addr = 190d0cc9 bp_read(190d0cc8) memory_value_bytes = [40, 93, 1e, 1d]
```

For some reason I have a hunch that something we're doing in the Rust layer is causing the RAM in this area to be so different than the C version (I've compared the values over and over through iterations to see how they change) that it just isn't getting a valid firmware patch upload...

**Pull request closed without merging**
