### PR TITLE
Made `Ticker::next` `Send+Sync`.

### LINKED ISSUE #2748: Should the future returned by `embassy_time::Ticker::next` be `Send + Sync + 'static`?
In exploring the possibilities for an `embedded-hal-async` trait for `Ticker`s I noticed, that the future returned by the function mentioned in the title isn't `Send + Sync + 'static`. Is this intentional? My tests so far have shown, that adding this bound doesn't negatively effect the tests I ran.

### PR DESCRIPTION
**Pull request by Frostie314159**
This PR makes the `Future` returned by `embassy_time::Ticker::next` `Send+Sync`. This resolves #2748. Since `embassy_time::Timer` is already a `Future` and it already is `Send+Sync`, no further changes were necessary on that end.

### CODE REVIEW

**Comment by Frostie314159** [comment]
CI-Failure appears unrelated.

**Comment by Frostie314159** [comment]
We can't make this `Future` `'static`, since the `poll_fn` takes in a non-static mutable reference to `self`.

**Review by Dirbaio — APPROVED** [review]
thanks!

**Comment by Dirbaio** [comment]
to fix CI, rebase your commit on top of latest git main.

**Comment by Frostie314159** [comment]
Done

**Review by Dirbaio — APPROVED** [review]
thanks!

**Pull request merged**
