### PR TITLE
cyw43: add support for WPA3 and more extensive security options.

### PR DESCRIPTION
**Pull request by Dirbaio**
what it says on the tin.

cc @andrewdavidmackenzie can you give this a test? It can successfully join a mikrotik AP configured to do WPA3 only.

- **cyw43: use enum for ioctl instead of consts.**
- **cyw43: log ioctls.**
- **cyw43: add support for WPA3 and more extensive security options.**

### CODE REVIEW

**Comment by andrewdavidmackenzie** [comment]
I'll need to swing by the office, where we have WPA3. Can do today or tomorrow. Is that soon enough?

**Comment by Dirbaio** [comment]
ah it's a corp network. Is it using WPA3 Personal or Enterprise? Enterprise is totally different and will require quite a bit of work to support.

**Comment by andrewdavidmackenzie** [comment]
Hmmm... Seems to have changed from WPA3 to WPA2 Personal during my week of PTO! :-(
Not convinced this is not "Pilot error", so let me try a bit more....

`#[non_exhaustive]`

```
rror[E0639]: cannot create non-exhaustive struct using struct expression
   --> src/porky.rs:169:23
    |
169 |               "open" => JoinOptions {
    |  _______________________^
170 | |                 auth: JoinAuth::Open,
171 | |                 ..Default::default()
172 | |             },
````

Ouch...

**Comment by andrewdavidmackenzie** [comment]
No worries:
```
        let mut join_options = JoinOptions::new(ssid_pass.as_bytes());

        match SSID_SECURITY {
            "open" => join_options.auth = JoinAuth::Open,
            "wpa" => join_options.auth = JoinAuth::Wpa,
            "wpa2" => join_options.auth = JoinAuth::Wpa2,
            "wpa3" => join_options.auth = JoinAuth::Wpa3,
            _ => {
                error!("Security '{}' is not supported", SSID_SECURITY);
                return None;
            }
        };
```

**Comment by andrewdavidmackenzie** [comment]
I've just tested the same code (shown above) trying to connect to my Personal (Android) hotspot with WPA2-Personal and WPA3-Personal.

WPA2-Personal   --> OK
WPA3-Personal   --> No luck.

**Comment by andrewdavidmackenzie** [comment]
On the Corporate network (now using WPA2 Personal according to my Mac), I cannot connect at all. :-(

**Comment by andrewdavidmackenzie** [comment]
On my home WPA2 network - no issues, all OK.

**Pull request merged**
