### PR TITLE
rtc: cleanup and consolidate

### PR DESCRIPTION
**Pull request by xoviat**
This removes an extra file that I left in, adds an example, and consolidates the files into one 'v2' file.

### CODE REVIEW

**Comment by MathiasKoch** [comment]
Given both this & the former PR with RTC that was merged for stm32, have you tried it on actual hardware?

It seems to me like it is still missing some LS(I/E) Rcc configs?

**Comment by Dirbaio** [comment]
RTC is the perfect thing to write HIL tests for, since it doesn't require external hardware. If any of you guys is up for it I can give you teleprobe access, so you can remotely run the tests on any of the boards in the test farm.

**Comment by xoviat** [comment]
bors try

**Review by Dirbaio — APPROVED** [review]
LGTM! Thanks!

bors r+

**Pull request merged**
