### PR TITLE
embassy-time: Introduce reset function for Ticker.

### PR DESCRIPTION
**Pull request by Frostie314159**
This PR attempts to allow resetting the Ticker in embassy-time. This could prove useful for the implementation of some network protocols, which require precise timing alignments.

### CODE REVIEW

**Review by Dirbaio — APPROVED** [review]
thanks!

**Comment by Dirbaio** [comment]
could you fix CI? it's failing because you didn't rustfmt the file.

**Comment by Frostie314159** [comment]
Ah. That's what was causing the issue. Sure I'll get back to it tomorrow.

**Comment by Frostie314159** [comment]
The CI, refuses to run.

**Comment by Dirbaio** [comment]
bender run

**Pull request merged**
