### PR TITLE
Rpi Pico PIO driver

### PR DESCRIPTION
**Pull request by fluffware**
This is a driver for the two PIOs in the Pico. I've tried using the type system to get as much compile time checks as possible. There is asynchronous support for FIFOs an Irqs. No DMA support yet. There's an example that shows how to use the driver asynchronously.

### CODE REVIEW

**Comment by kalkyl** [comment]
Awesome! Already successfully using this in a current project :)

**Review by nvx — COMMENTED** [review]
I noticed a mix-up of in/out in one of the examples based on my testing.

It also seems that we're missing the ability to specify the jmp pin. Looks like `set_jmp_pin` exists under `execctrl` register rather than `pinctrl` which I imagine is how it got missed.

Finally is there any reason the PioPin pin() func is private? Being public would be a little more convenient in some cases (saves having to save a copy of the pin number before converting it to a PioPin)

Awesome functionality in general though!

**Comment by nvx** [comment]
I discovered `JMP` instructions behaving incorrectly when loaded at non-zero origins (the only jmp in the example applications is coincidentally in a program loaded at origin 0 so it behaves correctly there).

I initially thought this was a bug with the Rust PIO assembler (https://github.com/rp-rs/pio-rs/issues/34), but looks like its behaviour is consistent with the C SDK and it's up to the PIO loader to correct the JMP offsets.

**Comment by lulf** [comment]
Could you rebase the PR?

**Comment by nvx** [comment]
@fluffware did you have any thoughts on the relative jmp issue before this gets merged? It looks like it shouldn't be too hard to fix (can leverage code from the other rust program loader). Happy to submit a PR if needed (PR to your ksb_pio branch I guess?)

**Comment by fluffware** [comment]
> @fluffware did you have any thoughts on the relative jmp issue before this gets merged? It looks like it shouldn't be too hard to fix (can leverage code from the other rust program loader). Happy to submit a PR if needed (PR to your ksb_pio branch I guess?)

I think that belongs in pio-rs, either as an option when parsing or a fix-up afterwards (like a link-editor).

**Comment by nvx** [comment]
> > @fluffware did you have any thoughts on the relative jmp issue before this gets merged? It looks like it shouldn't be too hard to fix (can leverage code from the other rust program loader). Happy to submit a PR if needed (PR to your ksb_pio branch I guess?)
> 
> I think that belongs in pio-rs, either as an option when parsing or a fix-up afterwards (like a link-editor).

Currently rp-hal does this fixup not pio-rs when not using embassy - see the code at https://github.com/rp-rs/rp-hal/blob/4b2b33b950d06ad690cde7088db2545e39f02221/rp2040-hal/src/pio.rs#L193

I believe this mimics the behaviour of the C pico sdk as well. We can certainly decide to do things differently, but I daresay there would have to be a good reason for deviating from way everywhere else does it.

**Comment by fluffware** [comment]
> > > @fluffware did you have any thoughts on the relative jmp issue before this gets merged? It looks like it shouldn't be too hard to fix (can leverage code from the other rust program loader). Happy to submit a PR if needed (PR to your ksb_pio branch I guess?)
> > 
> > 
> > I think that belongs in pio-rs, either as an option when parsing or a fix-up afterwards (like a link-editor).
> 
> Currently rp-hal does this fixup not pio-rs when not using embassy - see the code at https://github.com/rp-rs/rp-hal/blob/4b2b33b950d06ad690cde7088db2545e39f02221/rp2040-hal/src/pio.rs#L193
> 
> I believe this mimics the behaviour of the C pico sdk as well. We can certainly decide to do things differently, but I daresay there would have to be a good reason for deviating from way everywhere else does it.

I think everyone else is doing it wrong :-) The fixup manipulates the instructions and needs knowledge of how they are encoded. This has little to do with getting the code to run on the hardware.
Ok, how about this? Let's wrap the program in a new class, let's call it ResolvedProgram, which gives a new view of the program  with all the addresses adjusted. This way we don't mix the encoding aware code with the rest. Hopefully that class could be part of pio-rs at some point.

**Review by lulf — APPROVED** [review]
Looking forward to play with this, thanks for working on it!

bors r+

**Comment by kalkyl** [comment]
All i wanted for xmas!

**Review by lulf — COMMENTED** [review]
I wonder if this is breaking the rp GPIO CI test. Does the test need to be modified or is it catching a real issue?

**Comment by kalkyl** [comment]
> 

I saw this PR changes `write` into `modify` in gpio `set_pull`, this is not right? I guess that's why the CI fails because it's not reseting the pulls...

**Comment by fluffware** [comment]
> > 
> 
> I saw this PR changes `write` into `modify` in gpio `set_pull`, this is not right? I guess that's why the CI fails because it's not reseting the pulls...
Unless I've completely misunderstood how modify works this is correct. Using write would overwrite any other settings done on the pad control register. What is not correct is that the unused pulls are not cleared.  I'll fix that.

**Comment by kalkyl** [comment]
> > > 
> 
> > 
> 
> > I saw this PR changes `write` into `modify` in gpio `set_pull`, this is not right? I guess that's why the CI fails because it's not reseting the pulls...
> 
> 
> 
> Unless I've completely misunderstood how modify works this is correct. Using write would overwrite any other settings done on the pad control register. What is not correct is that the unused pulls are not cleared.  I'll fix that.
> 
> 

Ahh yes sorry, didn't see you added those other fns that also mess with the pad_ctrl reg, so your latest addition should be right yeah :)

**Pull request merged**
