### PR TITLE
fix: nightly api changed during the night

### PR DESCRIPTION
**Pull request by Ddystopia**
https://doc.rust-lang.org/nightly/core/task/struct.Waker.html#method.data

https://doc.rust-lang.org/nightly/core/task/struct.Waker.html#method.vtable

### CODE REVIEW

**Comment by Ddystopia** [comment]
ci probably needs to be updated too

**Comment by diondokter** [comment]
Probably also need update the rust-toolchain.toml file

**Comment by Ddystopia** [comment]
> Probably also need update the rust-toolchain.toml file

I'm not sure how embassy project is structured, would this be enough?

```diff
rust-toolchain-nightly.toml

< channel = "nightly-2024-09-"
---
> channel = "nightly-2024-09-06"
```

**Comment by diondokter** [comment]
Looks good IMO

**Pull request merged**
