### PR TITLE
Add assume_noise_free to usart configuration

### PR DESCRIPTION
**Pull request by rmja**
Effectively setting cr3.onebit

### CODE REVIEW

**Review by Dirbaio — APPROVED** [review]
Thanks!

bBors r+

**Comment by rmja** [comment]
I made https://github.com/embassy-rs/stm32-data/pull/191 to fix the build error

**Comment by Dirbaio** [comment]
stm32-metapac v8 released.

Also, USARTv1 doesn't have that bit, you'll have to cfg it out.

**Review by Dirbaio — APPROVED** [review]
Thanks!

bors r+

**Comment by Dirbaio** [comment]
oh oops, you'll need to update stm32-metapac in Cargo.toml.

bors cancel
bors d+

**Comment by rmja** [comment]
@Dirbaio  there are now completely unrelated build errors, any ideas?

**Comment by Dirbaio** [comment]
could you please do the fixups for the unrelated PAC changes? I know it's unrelated, sorry about that, but it's the way to get this unstuck :(

**Comment by rmja** [comment]
I already did - see #1485

**Review by Dirbaio — APPROVED** [review]
bors d+

**Pull request merged**
