### PR TITLE
Add button_events example for stm32f3

### PR DESCRIPTION
**Pull request by ceigel**
This is a more elaborate example of using buttons and leds. 
Tested on STM32F3DISCOVERY

### CODE REVIEW

**Review by Dirbaio — APPROVED** [review]
Wow, this is a nice demo of more advanced async usage, like `with_timeout` and channels. I like it! Thank you :) 

Feel free to merge after fixing rustfmt.

bors d+

**Comment by Dirbaio** [comment]
oh you fixed it as I was writing! 

bors r+

**Comment by ceigel** [comment]
@Dirbaio thanks.

**Comment by ceigel** [comment]
@Dirbaio do you have an alternative for the led_blinker? It's kind of annoying that the button presses are only recognised after the leds.blink().await is done. But I don't know if it's worth fixing it and how to fix it.

**Comment by Dirbaio** [comment]
you can use [`select`](https://docs.rs/futures/latest/futures/future/fn.select.html) on `leds.blink()` and `queue.recv()`, so that if the `recv` completes, you immediately abort the blink and react.

**Comment by ceigel** [comment]
I might try that in a separate PR. It's night at my time zone and I don't like to program too late.

**Pull request merged**
