### PR TITLE
Add types for channel dynamic dispatch

### PR DESCRIPTION
**Pull request by lulf**
* Add internal DynamicChannel trait implemented by Channel that allows
  polling for internal state in a lock safe manner and does not require
  knowing the channel size.
* Existing usage of Sender and Receiver is preserved and does not use
  dynamic dispatch.
* Add DynamicSender and DynamicReceiver types that references the
  channel using the DynamicChannel trait and does not require the const
  generic channel size parameter.

Having the ability not know the channel size is very convenient when you don't want to change all of your channel using code when tuning the size. With this change, existing usage can be kept, and those willing to pay the price for dynamic dispatch may do so.

### CODE REVIEW

**Comment by huntc** [comment]
> Having the ability not know the channel size is very convenient when you don't want to change all of your channel using code when tuning the size. With this change, existing usage can be kept, and those willing to pay the price for dynamic dispatch may do so.

Doesn’t a simple type alias also achieve the same goal ie a type alias requires a change in just one place…?

**Comment by lulf** [comment]
@huntc If you control the entire code base, yes. But if you expose an API in in one crate, and want consumers of your API to not consider the queue size, I believe this is a much nicer way. Using Channel in in Drogue Actor, the library can now expose an Address handle for the actor that doesn't need to have the channel size as a type parameter. Then I can use this address handle in another library that doesn't need to care about the queue size etc.

**Comment by lulf** [comment]
For the 'try' synchronous operations of the channel, I was able to work around this by adding a 'wrapper trait'. However, for async and GAT, the trait would need to have an associated type, which in turn requires specifying the associated types whenever using the trait, so that approach does not work.

Having the functionality in the Channel impl itself is the better way IMHO.

**Comment by lulf** [comment]
Some performance numbers


## Static on master

#### Size:
    Finished release [optimized] target(s) in 28.68s
   text    data     bss     dec     hex filename
  13208     104    1444   14756    39a4 channel_sender_receiver

#### Stack:
(HOST) INFO  reading 254.49 KiB of RAM for stack usage estimation
(HOST) INFO  program has used at least 0.21/254.49 KiB (0.1%) of stack space


## Static on branch (should be the same as on master)

#### Size:
    Finished release [optimized] target(s) in 29.89s
   text    data     bss     dec     hex filename
  13208     104    1444   14756    39a4 channel_sender_receiver

#### Stack:
(HOST) INFO  reading 254.49 KiB of RAM for stack usage estimation
(HOST) INFO  program has used at least 0.21/254.49 KiB (0.1%) of stack space



## Dynamic on branch

#### Size:
   Compiling embassy-nrf-examples v0.1.0 (/home/lulf/dev/embassy/examples/nrf)
    Finished release [optimized] target(s) in 0.30s
   text    data     bss     dec     hex filename
  13244     104    1468   14816    39e0 channel_sender_receiver_dyn


#### Stack:
(HOST) INFO  reading 254.46 KiB of RAM for stack usage estimation
(HOST) INFO  program has used at least 0.22/254.46 KiB (0.1%) of stack space

**Comment by Dirbaio** [comment]
let's do this :rocket: 

bors r+

**Pull request merged**
