### PR TITLE
(embassy-rp): Allow upgrading a blocking uart to a BufferedUart

### PR DESCRIPTION
**Pull request by MathiasKoch**
Also implement blocking embedded-nal serial traits for BufferedUart

### CODE REVIEW

**Comment by Dirbaio** [comment]
LGTM. Could you add a HIL test? Create a nonbuffered uart, transmit some data, then upgrade it to buffered, then transmit some more data. To test that the "upgrading" works.

**Comment by MathiasKoch** [comment]
Absolutely :+1:

**Review by Dirbaio — APPROVED** [review]
:ok_hand: :+1: 

bors r+

**Comment by Dirbaio** [comment]
you accidentally added some vscode and rust-toolchain files, could you fix?

bors d+

**Pull request merged**
