### PR TITLE
Issue 1986 add sai receiver driver

### PR DESCRIPTION
**Pull request by tyler-gilbert**
This PR adds synchronous and receiver capabilities to the newly created STM32 SAI driver.

Here is some sample code that is used to test. There are a few parts of this that are specific to my project (managing the peripherals) but nothing that isn't too difficult to deduce.

The SAI1 needs to be clone_unchecked to use with both the transmitter and receiver:

```rust
        Some(SaiTransmitterPeripherals {
            sai: unsafe { peripherals.SAI1.clone_unchecked() },
            fs: peripherals.PF9,
            sck: peripherals.PF8,
            sd: peripherals.PE3,
            mclk: peripherals.PF7,
            dma: peripherals.DMA2_CH4,
        }),
        Some(SaiReceiverPeripherals {
            sai: peripherals.SAI1,
            sd: peripherals.PE6,
            dma: peripherals.DMA2_CH1,
        }),
```

```rust
async fn execute(self: &mut Self) {
        const DMA_SAMPLE_COUNT: usize = 512;
        const FRAME_SAMPLE_COUNT: usize = DMA_SAMPLE_COUNT / 2;

        let mut dma_tx_buffer = [0u16; DMA_SAMPLE_COUNT];
        let mut dma_rx_buffer = [0u16; DMA_SAMPLE_COUNT];
        {
            use embassy_time::Duration;
            Timer::after(Duration::from_secs(2)).await;
        }
        use embassy_stm32::sai::{
            ClockStrobe, ComplementFormat, Config, FifoThreshold, MasterClockDivider, Sai,
        };

        info!("Starting SAI");
        let (tx_config, mut sai_transmitter) = {
            let tx_peripherals = singleton::get_mut()
                .peripherals
                .sai_transmitter
                .take()
                .unwrap();

            let tx_config = {
                let mut config = Config::default();
                config.mode = Mode::Master;
                config.tx_rx = TxRx::Transmitter;
                config.mute_detection_counter = embassy_stm32::dma::word::U5(0);
                config.master_clock_divider = MasterClockDivider::Div22;
                config.clock_strobe = ClockStrobe::Falling;
                config.fifo_threshold = FifoThreshold::Empty;
                config.complement_format = ComplementFormat::OnesComplement;
                config.is_sync_output = true;
                config
            };

            (
                tx_config.clone(),
                Sai::new_asynchronous_block_b_with_mclk(
                    tx_peripherals.sai,
                    tx_peripherals.sck,
                    tx_peripherals.sd,
                    tx_peripherals.fs,
                    tx_peripherals.mclk,
                    tx_peripherals.dma,
                    &mut dma_tx_buffer,
                    tx_config,
                ),
            )
        };

        let mut sai_receiver = {
            let rx_config = {
                let mut config = tx_config.clone();
                config.mode = Mode::Slave;
                config.tx_rx = TxRx::Receiver;
                config.is_sync_output = false;
                config
            };

            let rx_peripherals = singleton::get_mut()
                .peripherals
                .sai_receiver
                .take()
                .unwrap();

            Sai::new_synchronous_block_a(
                rx_peripherals.sai,
                rx_peripherals.sd,
                rx_peripherals.dma,
                &mut dma_rx_buffer,
                rx_config,
            )
        };

        let signal = {
            let mut real_signal = core_dsp::signal::RealSignal::<FRAME_SAMPLE_COUNT>::new(8000);
            real_signal.add_tone(440.0, 0.5);
            real_signal.add_tone(2440.0, 0.5);

            let mut signal = [0u16; FRAME_SAMPLE_COUNT];
            for (i, sample) in real_signal.data.iter().enumerate() {
                signal[i] = (i * 65535 / FRAME_SAMPLE_COUNT) as u16;
            }
            signal
        };

        for value in signal.iter() {
            info!("Signal value: {}", value);
        }

        sai_receiver.start();
        sai_transmitter.start();

        let mut rx_signal = [0u16; FRAME_SAMPLE_COUNT];

        loop {
            info!("Write SAI frame");
            match sai_transmitter.write(&signal as &[u16]).await {
                Ok(_) => {}
                Err(e) => {
                    warn!("Error writing to SAI: {:?}", e);
                }
            }
            match sai_receiver.read(&mut rx_signal).await {
                Ok(_) => {}
                Err(e) => {
                    warn!("Error reading from SAI: {:?}", e);
                }
            }

            for (i, value) in rx_signal.iter().enumerate() {
                if *value != signal[i] {
                    info!("[{}]: {} != {}", i, value, signal[i]); //we don't want to see this
                    break;
                }
            }
        }
    }
```

### CODE REVIEW

**Comment by xoviat** [comment]
Do you think you could add split structs like the uarttx and uartrx that we have so that clone_unchecked doesn't have to be used in user code?

**Comment by tyler-gilbert** [comment]
@xoviat, I will take a look. I think something like that should work.

**Comment by tyler-gilbert** [comment]
@xoviat, I separated the blocks so the unsafe clone happens in the driver. Maybe there is a better way. I am open to suggestions.

**Comment by xoviat** [comment]
unsafe within embassy itself is fine. I just don't want to require it for users, if possible.

**Pull request merged**
