### PR TITLE
Prevent UART from only getting 0s from the output

### PR DESCRIPTION
**Pull request by mvniekerk**

### CODE REVIEW

**Comment by Dirbaio** [comment]
accidentally added `.idea` dir

**Comment by Dirbaio** [comment]
can you squash the 2 commits together so it doesn't show up in history?

**Comment by mvniekerk** [comment]
> accidentally added `.idea` dir

Fixed, saw that as well

**Comment by mvniekerk** [comment]
Will try to squash the commits

**Pull request closed without merging**
