### PR TITLE
fix(stm32): Align FMC with new versions from stm32-data

### PR DESCRIPTION
**Pull request by rmja**

### CODE REVIEW

**Comment by rmja** [comment]
This should only be merged after https://github.com/embassy-rs/stm32-data/pull/166 is merged and the `stm32-data` submodule updated!

**Comment by Dirbaio** [comment]
> and the stm32-data submodule updated!

can you update it, in this PR?

**Comment by rmja** [comment]
@Dirbaio I hope that should do it

**Comment by rmja** [comment]
Do not merge this yet. I found out that the stm data is not complete...

**Comment by rmja** [comment]
I think this is ready now.

**Comment by lulf** [comment]
Thanks! 

bors r+

**Pull request merged**
