### PR TITLE
stm32/usart: configurable readback for half-duplex to support 1-wire + ds18b20 example

### PR DESCRIPTION
**Pull request by trnila**
The 1-Wire bus requires the ability to read data while transmission is in progress to detect if a sensor pulls the bus to a low level (logic 0).
This pull request adds a new enum `HalfDuplexReadback` with `Readback` variant that keeps receiver enabled during transmission. Half duplex can be newly created with `BufferedUart` (#3278). A simplified example, based on the RP example, has been added to demonstrate how to use this feature with the DS18B20 temperature sensor.

### CODE REVIEW

**Review by Dirbaio — APPROVED** [review]
thank you!

**Comment by wrs** [comment]
@trnila Thanks for half-duplex BufferedUart! With readback off, it appears to me that the RE flag is never turned back on after a transmission is complete, so reception doesn't work. If I manually set it after sending, then receiving works. Just wanted to check if I'm missing something before I file an issue and/or try to make a fix.

```rust
        self.tx.write_all(&buf).await?;
        self.tx.flush().await.unwrap();
        // Need to manually enable the receiver after tx is done
        embassy_stm32::pac::USART2.cr1().modify(|w| w.set_re(true));
```

**Comment by trnila** [comment]
Looks like transmitter should be enabled forever (`TE`) after the first write in case of `BufferedUart` (is that even an issue? it could just reduce power consumption a bit?).

Receiver seems to be really disabled forever with readback off after the first transmission. 
I think we could reenable `RE` in [interrupt](https://github.com/embassy-rs/embassy/blob/897d42e01214396b448e5aae06a4186a4c282e7a/embassy-stm32/src/usart/buffered.rs#L90) once all bytes were successfully transmitted (so no bytes are lost between `write` and calling to `read`)?
But there can be issues with FIFO and readback-off: The receiver could be potentially turned on while transmission of last character is in progress and hence receiving that character back. Maybe [TXE and empty tx buffer](https://github.com/embassy-rs/embassy/blob/897d42e01214396b448e5aae06a4186a4c282e7a/embassy-stm32/src/usart/buffered.rs#L120) could be better for enabling receiver. Currently I am without hardware, so I cannot test myself.

**Comment by wrs** [comment]
That makes sense. I am on an F1 so I can't see the effects of the FIFO. My working C driver sets RE in the TC interrupt handler if the tx buffer is empty. I'll give that a try.

I'm thinking it might make sense for the driver to manage an optional output pin for transceiver output enable (similar to CS pin handling in the SPI driver), for when half duplex mode is used with an RS-485 transceiver. It just needs to follow the TE/RE changes.

**Pull request merged**
