### PR TITLE
Move frequency to SPI config

### PR DESCRIPTION
**Pull request by bofh**
This will move stm32-spi frequency settings from function parameters to config, see #1682.

Tested on NUCLEO-F303K8, not tested for #[cfg(any(spi_v3, spi_v4, spi_v5))] variant.

### CODE REVIEW

**Comment by xoviat** [comment]
why was this closed?

**Comment by bofh** [comment]
accidentally

**Comment by Dirbaio** [comment]
looks good! Can you change the examples so that they all show how to set the frequency? It's a very basic thing that everyone using SPI will need, so it's nice that the examples show how to do it.

**Review by Dirbaio — APPROVED** [review]
thanks!

**Comment by bofh** [comment]
Good point

**Pull request merged**
