### PR TITLE
Fixing missing re-export

### PR DESCRIPTION
**Pull request by busslina**
cyw::ScanOptions

### CODE REVIEW

**Comment by busslina** [comment]
Seems solved:
imagen

**Review by Dirbaio — APPROVED** [review]
thanks!

**Comment by Dirbaio** [comment]
CI fails because that struct is now public without docs. could you add some?

**Comment by busslina** [comment]
Formmat failed. I'm on it

**Comment by busslina** [comment]
I executed `rustfmt.exe .\lib.rs` but I'm getting an error because I'm not on `nightly channel`. So formmating seems not working. Also with VSCode isn't doing anything:

imagen

**Comment by Dirbaio** [comment]
try `cargo +nightly fmt` in the `cyw43` dir

**Comment by busslina** [comment]
Ok, so passing `--edition 2021` made it work. As I supposed, was an alphabetical order issue.

**Comment by Dirbaio** [comment]
thanks!

**Pull request merged**
