### PR TITLE
Add uart::Read DMA-based implementation

### PR DESCRIPTION
**Pull request by lulf**
* Rename existing read() to bread() (blocking)

Only tested with v2 usart on L0.

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
"bread" because of function name clashes? Do appropriate trait `use` statements not disambiguate?

If we need to rename, I think I'd prefer `read_blocking(...)` to parallel `read_dma(...)` mayhap.

**Comment by Dirbaio** [comment]
I'm not sure about the `bread` name either. First, it looks with bread :bread: . Second, the `b` prefix like in `bwrite` [will be removed](https://github.com/rust-embedded/embedded-hal/pull/280) in embedded-hal. `read_blocking` sounds better.

Unfortunately there's no blocking uart read trait in embedded-hal :S

**Comment by lulf** [comment]
> I'm not sure about the `bread` name either. First, it reads like bread bread . Second, the `b` prefix like in `bwrite` [will be removed](https://github.com/rust-embedded/embedded-hal/pull/280) in embedded-hal. `read_blocking` sounds better.
> 

This ^^ was the reason for naming it :bread: , but I agree `read_blocking` is way better. In any case, :bread: sounds better as a type:

```rust
impl Bread {
   fn slice() -> &[BreadSlice];
}
```

**Review by Dirbaio — APPROVED** [review]
LGTM now that the :bread: is gone :) 

Thank you!

**Pull request merged**
