### PR TITLE
embassy-boot (rp): Add WatchdogFlash

### PR DESCRIPTION
**Pull request by kalkyl**

### CODE REVIEW

**Comment by Dirbaio** [comment]
Integrating it into the flash feels a bit hacky.

Perhaps we should add support for passing a watchdog into the bootloader? It would be yet another generic param though, so I'm not sure...

**Comment by kalkyl** [comment]
> Integrating it into the flash feels a bit hacky.
> 
> Perhaps we should add support for passing a watchdog into the bootloader? It would be yet another generic param though, so I'm not sure...

Yeah, i just mirroring the functionality of the nrf version here - i've been using it like this myself for a while and just thought i'd upstream it, but i agree it feels a little hacky...

**Comment by Dirbaio** [comment]
Oh, I wasn't aware nrf already did it this way. If so, I'm fine with doing it for rp too for now. We can revisit in the future.

**Review by Dirbaio — APPROVED** [review]
bors r+

**Pull request merged**
