### PR TITLE
add TL maibox for stm32wb

### PR DESCRIPTION
**Pull request by OueslatiGhaith**
Hello,

This pull request is related to #1397 and #1401, inspired by #24, build upon the work done in #1405, and was tested on an stm32wb55rg.

This pull request aims to add the transport layer mailbox for stm32wb microcontrollers. For now it's only capable of initializing it and getting the firmware information

### CODE REVIEW

**Comment by xoviat** [comment]
@OueslatiGhaith Thanks for bearing with us so far; I am trying to make time for this when I can.

One question though: is the example supposed to work as-is on nucleo-stm32wb55rg? Because I noticed that it wasn't able to initialize the mailbox.

**Comment by OueslatiGhaith** [comment]
hello @xoviat , thank you for taking a look at this.

the example code should keep looping until the CPU2 fills out the firmware info region in the shared SRAM. On my nucleo board, I've flashed the firmware for the radio coprocessor provided by ST, I'm not sure if it's pre-installed or not, though.

**Comment by xoviat** [comment]
bors try

**Comment by Dirbaio** [comment]
Updated FUS and stack to `stm32wb5x_BLE_Stack_full_extended_fw.bin`, now the versions look like this:

screenshot-2023-05-04_01-37-52

running the tl_mbox example hardfaults:

```
stack backtrace:
   0: HardFaultTrampoline
      <exception entry>
   1: compiler_builtins::mem::impls::copy_forward::copy_forward_aligned_words
        at /cargo/registry/src/index.crates.io-6f17d22bba15001f/compiler_builtins-0.1.91/src/mem/impls.rs:46:13
   2: compiler_builtins::mem::impls::copy_forward
        at /cargo/registry/src/index.crates.io-6f17d22bba15001f/compiler_builtins-0.1.91/src/mem/impls.rs:112:13
   3: compiler_builtins::mem::memcpy
        at /cargo/registry/src/index.crates.io-6f17d22bba15001f/compiler_builtins-0.1.91/src/mem/mod.rs:26:9
   4: embassy_stm32::tl_mbox::TlMbox::init
        at /home/dirbaio/embassy/embassy/embassy-stm32/src/tl_mbox/mod.rs:290:13
   5: tl_mbox::____embassy_main_task::{{closure}}
        at src/bin/tl_mbox.rs:19:16
   6: embassy_executor::raw::TaskStorage<F>::poll
        at /home/dirbaio/embassy/embassy/embassy-executor/src/raw/mod.rs:164:15
   7: embassy_executor::raw::SyncExecutor::poll::{{closure}}
        at /home/dirbaio/embassy/embassy/embassy-executor/src/raw/mod.rs:431:17
   8: embassy_executor::raw::run_queue::RunQueue::dequeue_all
        at /home/dirbaio/embassy/embassy/embassy-executor/src/raw/run_queue.rs:85:13
   9: embassy_executor::raw::SyncExecutor::poll
        at /home/dirbaio/embassy/embassy/embassy-executor/src/raw/mod.rs:411:13
  10: embassy_executor::raw::Executor::poll
        at /home/dirbaio/embassy/embassy/embassy-executor/src/raw/mod.rs:537:6
  11: embassy_executor::arch::thread::Executor::run
        at /home/dirbaio/embassy/embassy/embassy-executor/src/arch/cortex_m.rs:71:21
  12: tl_mbox::__cortex_m_rt_main
        at src/bin/tl_mbox.rs:11:1
  13: main
        at src/bin/tl_mbox.rs:11:1
  14: Reset
```

which is zerofilling EVT_POOL: https://github.com/OueslatiGhaith/embassy/blob/tl_mbox/embassy-stm32/src/tl_mbox/mod.rs#L290

Hardcoding so many addresses in `memory.x` scares me a bit: https://github.com/OueslatiGhaith/embassy/blob/tl_mbox/examples/stm32wb/memory.x#L22-L40
For example, the EVT_POOL size is calculated with [this const](https://github.com/OueslatiGhaith/embassy/blob/tl_mbox/embassy-stm32/src/tl_mbox/mod.rs#L31) which evaluates to 0x53c based on the current settings. This is exactly the distance between EVT_POOL (set to 0x200303c0 in memory.x) and the next addr (BLE_CMD_BUFFER, 0x200308fc). However, if the consts are changed, the addresses have to change. It feels to me that this could be a struct, so all the offsets are automatically calculated based on the chosen consts, instead of hardcoded.

**Comment by Dirbaio** [comment]
result with `stm32wb5x_BLE_Stack_full_fw.bin`:

```
[dirbaio@mars stm32wb]$ probe-run --chip STM32WB55CCUx --speed 1000 --connect-under-reset target/thumbv7em-none-eabihf/debug/tl_mbox
(HOST) INFO  flashing program (55 pages / 55.00 KiB)
(HOST) INFO  success!
────────────────────────────────────────────────────────────────────────────────
0.000000 DEBUG rcc: Clocks { sys: Hertz(16000000), apb1: Hertz(16000000), apb1_tim: Hertz(16000000), apb2: Hertz(16000000), apb2_tim: Hertz(16000000), ahb1: Hertz(16000000), ahb2: Hertz(16000000), ahb3: Hertz(16000000) }
└─ embassy_stm32::rcc::set_freqs @ /home/dirbaio/embassy/embassy/embassy-stm32/src/fmt.rs:125
0.000122 INFO  Hello World!
└─ tl_mbox::____embassy_main_task::{async_fn#0} @ src/bin/tl_mbox.rs:14
0.001068 ERROR not yet initialized
└─ tl_mbox::____embassy_main_task::{async_fn#0} @ src/bin/tl_mbox.rs:24
0.001586 ERROR not yet initialized
└─ tl_mbox::____embassy_main_task::{async_fn#0} @ src/bin/tl_mbox.rs:24
0.002105 ERROR not yet initialized
└─ tl_mbox::____embassy_main_task::{async_fn#0} @ src/bin/tl_mbox.rs:24
0.002716 INFO  version 0.0.0 - SRAM2a 1 - SRAM2b 16
└─ tl_mbox::____embassy_main_task::{async_fn#0} @ src/bin/tl_mbox.rs:33

**Comment by OueslatiGhaith** [comment]
I've tested almost all firmware binaries from version 1.15.0 all the way back to version 1.13.0, and they all seem to be working fine, at least on my end, I've also tested them with the `bluetooth-hci` implementation I had.
But version 1.16.0 doesn't seem to work, there may be some breaking changes in that version, even though the release notes don't seem to indicate such a change.
@Dirbaio can you give it a try with a previous version?

**Comment by xoviat** [comment]
bors try

**Comment by xoviat** [comment]
I was able to get this to work with the latest FUS. I think this is good enough to start with for now, and we'll make further improvements.

This may help you in implementing OTA update functionality, if that's something you would like to work on:

https://github.com/STMicroelectronics/STM32CubeWB/blob/fd3d1c1ca7052bb526b9735b51a9109102c61bac/Projects/P-NUCLEO-WB55.Nucleo/Applications/BLE/BLE_Ota/Core/Src/app_entry.c#L218

**Pull request merged**
