### PR TITLE
Async Pipe

### PR DESCRIPTION
**Pull request by Dirbaio**

### CODE REVIEW

**Review by lulf — CHANGES_REQUESTED** [review]
LGTM, but shouldn't the original ring_buffer be removed from embassy-hal-common/src/ring_buffer.rs?

**Comment by Dirbaio** [comment]
it's still used by BufferedUart (nrf, stm32), and it's slightly different (it borrows the buffer instead of owning it with const generics).

(also note the new ringbuffer is not public API)

**Review by lulf — APPROVED** [review]
Looks like a great addition in my view!

**Pull request merged**
