### PR TITLE
stm32/uart: add swap_rx_tx

### PR DESCRIPTION
**Pull request by alepez**
Add an option to swap RX and TX. Tested on STM32U575ZITx on a board with swapped tx/rx pins.

### CODE REVIEW

**Comment by alepez** [comment]
CI is failing, I guess because it is some tests and examples are using uart without the `swap` bitfield in `cr2`. How can I fix this?

**Comment by Dirbaio** [comment]
check [here](https://github.com/embassy-rs/stm32-data/tree/main/data/registers) which uart versions have the swap bit, gate it with `cfg`s. For example, #[cfg(usart_v4)]` if only v4 has it.

**Comment by alepez** [comment]
I think this:

```rs
        #[allow(unused_variables)]
        let swap_rx_tx = false;

        #[cfg(any(usart_v3, usart_v4))]
        let swap_rx_tx = config.swap_rx_tx;

        if swap_rx_tx {
            let (rx, tx) = (tx, rx);
            rx.set_as_af(rx.af_num(), AFType::Input);
            tx.set_as_af(tx.af_num(), AFType::OutputPushPull);
        } else {
            rx.set_as_af(rx.af_num(), AFType::Input);
            tx.set_as_af(tx.af_num(), AFType::OutputPushPull);
        }
```

can be changed to this:

```rs
        cfg_if::cfg_if! {
            if #[cfg(any(usart_v3, usart_v4))] {
                if config.swap_rx_tx {
                    let (rx, tx) = (tx, rx);
                    rx.set_as_af(rx.af_num(), AFType::Input);
                    tx.set_as_af(tx.af_num(), AFType::OutputPushPull);
                } else {
                    rx.set_as_af(rx.af_num(), AFType::Input);
                    tx.set_as_af(tx.af_num(), AFType::OutputPushPull);
                }
            } else {
                rx.set_as_af(rx.af_num(), AFType::Input);
                tx.set_as_af(tx.af_num(), AFType::OutputPushPull);
            }
        }
```

There's a little more code repetition, but there are no warning to suppress and there's no runtime evaluation (even without compiler optimizations) of the flag when it is not available.

**Review by Dirbaio — APPROVED** [review]
Thank you!

**Pull request merged**
