### PR TITLE
rp: Allow zero len reads for buffered uart

### PR DESCRIPTION
**Pull request by timokroeger**
Prevents the read methods from getting stuck forever.

cc @MathiasKoch can you test if this fixes the problem you described in the chat?

### CODE REVIEW

**Comment by MathiasKoch** [comment]
Will give it a test first thing Monday morning 👌

**Comment by Dirbaio** [comment]
I think `write` has the same bug?

**Comment by timokroeger** [comment]
Indeed, added the same checks for the write methods.

**Review by Dirbaio — APPROVED** [review]
Thank you!

bors r+

**Pull request merged**
