### PR TITLE
Add examples for stm32g0

### PR DESCRIPTION
**Pull request by Adancurusul**
Add `usart ` `usart_dma`  `usart_buffered `  `irq ` `multiprio ` `adc ` examples for stm32g0

Tested correctly with `STM32G031G8Ux`

### CODE REVIEW

**Comment by Dirbaio** [comment]
can you fix CI?

**Comment by Adancurusul** [comment]
```
PS G:\codes\GithubProject\stm32g0embassy> cargo build --release --bin multiprio
   Compiling embassy-stm32g0-examples v0.1.0 (G:\codes\GithubProject\stm32g0embassy)
    Finished `release` profile [optimized + debuginfo] target(s) in 17.40s
PS G:\codes\GithubProject\stm32g0embassy> cargo run --release --bin multiprio  
    Finished `release` profile [optimized + debuginfo] target(s) in 0.59s
     Running `probe-rs run --chip STM32G031G8Ux target\thumbv6m-none-eabi\release\multiprio`
      Erasing ✔ [00:00:00] [###################################################################################################################################################################################################] 20.00 KiB/20.00 KiB @ 22.79 KiB/s (eta 0s )  Programming ✔ [00:00:03] [####################################################################################################################################################################################################] 19.00 KiB/19.00 KiB @ 6.05 KiB/s (eta 0s )    Finished in 4.164s
0.000000 TRACE BDCR ok: 00008200
└─ embassy_stm32::rcc::bd::{impl#3}::init @ G:\codes\GithubProject\embassy\embassy-stm32\src\fmt.rs:117
0.000000 DEBUG rcc: Clocks { hclk1: Some(Hertz(16000000)), hsi: Some(Hertz(16000000)), lse: None, lsi: None, pclk1: Some(Hertz(16000000)), pclk1_tim: Some(Hertz(16000000)), pll1_p: None, pll1_q: None, rtc: Some(Hertz(32000)), sys: Some(Hertz(16000000)) }
└─ embassy_stm32::rcc::set_freqs @ G:\codes\GithubProject\embassy\embassy-stm32\src\fmt.rs:130
0.000152 INFO      [med] Starting long computation
└─ multiprio::__run_med_task::{async_fn#0} @ src\bin\multiprio.rs:80
1.000244 INFO      [med] done in 993 ms
└─ multiprio::__run_med_task::{async_fn#0} @ src\bin\multiprio.rs:87
1.000549 INFO  [low] Starting long computation
└─ multiprio::__run_low_task::{async_fn#0} @ src\bin\multiprio.rs:97
1.715209 INFO      [med] Starting long computation
└─ multiprio::__run_med_task::{async_fn#0} @ src\bin\multiprio.rs:80
2.715301 INFO      [med] done in 993 ms
└─ multiprio::__run_med_task::{async_fn#0} @ src\bin\multiprio.rs:87
```

**Comment by Adancurusul** [comment]
This is strange, it compiles and works fine in my case
```
PS G:\codes\GithubProject\stm32g0embassy> cargo build --release --bin multiprio
   Compiling embassy-stm32g0-examples v0.1.0 (G:\codes\GithubProject\stm32g0embassy)
    Finished `release` profile [optimized + debuginfo] target(s) in 17.40s
PS G:\codes\GithubProject\stm32g0embassy> cargo run --release --bin multiprio  
    Finished `release` profile [optimized + debuginfo] target(s) in 0.59s
     Running `probe-rs run --chip STM32G031G8Ux target\thumbv6m-none-eabi\release\multiprio`
      Erasing ✔ [00:00:00] [###################################################################################################################################################################################################] 20.00 KiB/20.00 KiB @ 22.79 KiB/s (eta 0s )  Programming ✔ [00:00:03] [####################################################################################################################################################################################################] 19.00 KiB/19.00 KiB @ 6.05 KiB/s (eta 0s )    Finished in 4.164s
0.000000 TRACE BDCR ok: 00008200
└─ embassy_stm32::rcc::bd::{impl#3}::init @ G:\codes\GithubProject\embassy\embassy-stm32\src\fmt.rs:117
0.000000 DEBUG rcc: Clocks { hclk1: Some(Hertz(16000000)), hsi: Some(Hertz(16000000)), lse: None, lsi: None, pclk1: Some(Hertz(16000000)), pclk1_tim: Some(Hertz(16000000)), pll1_p: None, pll1_q: None, rtc: Some(Hertz(32000)), sys: Some(Hertz(16000000)) }
└─ embassy_stm32::rcc::set_freqs @ G:\codes\GithubProject\embassy\embassy-stm32\src\fmt.rs:130
0.000152 INFO      [med] Starting long computation
└─ multiprio::__run_med_task::{async_fn#0} @ src\bin\multiprio.rs:80
1.000244 INFO      [med] done in 993 ms
└─ multiprio::__run_med_task::{async_fn#0} @ src\bin\multiprio.rs:87
1.000549 INFO  [low] Starting long computation
└─ multiprio::__run_low_task::{async_fn#0} @ src\bin\multiprio.rs:97
1.715209 INFO      [med] Starting long computation
└─ multiprio::__run_med_task::{async_fn#0} @ src\bin\multiprio.rs:80
2.715301 INFO      [med] done in 993 ms
└─ multiprio::__run_med_task::{async_fn#0} @ src\bin\multiprio.rs:87
```

**Comment by Adancurusul** [comment]
The rustc version here is `rustc 1.79.0 (129f3b996 2024-06-10)`
```
PS G:\codes\GithubProject\stm32g0embassy> rustc --version
rustc 1.79.0 (129f3b996 2024-06-10)
PS G:\codes\GithubProject\stm32g0embassy> cargo build --release --bin multiprio
    Finished `release` profile [optimized + debuginfo] target(s) in 0.39s
```

**Pull request closed without merging**
