### PR TITLE
stm32: can: fd: allow TX buffers in FIFO mode

### PR DESCRIPTION
**Pull request by cschuhen**
Uses enum in pac introduced here: embassy-rs/stm32-data#429

Based on : https://github.com/embassy-rs/embassy/pull/2632
with added fix.

### CODE REVIEW

**Review by Dirbaio — APPROVED** [review]
thanks! :rocket:

**Comment by cschuhen** [comment]
I wondered what would happen if I sneaked in another change :)

**Comment by cschuhen** [comment]
The words "Queue" and "FIFO" are too close to synonyms for my liking.

**Review by Dirbaio — APPROVED** [review]
:rofl:

**Comment by Dirbaio** [comment]
seems  h7 hangs

**Comment by cschuhen** [comment]
Hmm, strange. I've got to head out, I'll have a look later.

**Comment by cschuhen** [comment]
@tcbennun FYI. Any comments on this? 

The patch is significant in length but really it is just pushing a bunch of things from happening at the end of the initial construction to the start of the start method. This is done to preserve order and is a good change in general I think for the future. For example if we want to allow more customisation later for things like H7 fdcanram.

**Comment by tcbennun** [comment]
> @tcbennun FYI. Any comments on this?
> 
> The patch is significant in length but really it is just pushing a bunch of things from happening at the end of the initial construction to the start of the start method. This is done to preserve order and is a good change in general I think for the future. For example if we want to allow more customisation later for things like H7 fdcanram.

LGTM if it builds and runs alright (I can test it Monday), thanks for the fixes!

**Pull request merged**
