### PR TITLE
enc28j60: check LSTAT on both bits 2 and 10

### PR DESCRIPTION
**Pull request by Qix-**
On rev6 of the enc28j60, pin 10 is indeed LSTAT. It appears 2 is also LSTAT depending on the revision, so this PR checks both (as 2 is specified to be 'always 0' in the correct case).

### CODE REVIEW

**Comment by xoviat** [comment]
@Qix- can you rustfmt?

**Comment by Qix-** [comment]
`cargo fmt` isn't showing any changes, is there a special command I should run?

**Comment by Dirbaio** [comment]
root cause of the issue found: https://github.com/embassy-rs/embassy/pull/1746/commits/075a48c61dc588a94097c61add7088e82a989f65

so thankfully the workaround is no longer needed. Thanks anyway for the PR! :)

**Comment by Qix-** [comment]
Ahhhhhh nice :D never been so satisfied to have a PR closed 😂 nice work.

**Pull request closed without merging**
