### PR TITLE
Salty update

### PR DESCRIPTION
**Pull request by lulf**

### CODE REVIEW

**Comment by Dirbaio** [comment]
bender run

**Comment by Dirbaio** [comment]
bender run

**Comment by lulf** [comment]
I've not checked the impact of code size or ram usage of this change.

**Comment by Dirbaio** [comment]
still fails with an empty cache. huh

**Comment by Dirbaio** [comment]
bender run

**Comment by Dirbaio** [comment]
bender run

**Comment by lulf** [comment]
Thanks @Dirbaio !

**Comment by Dirbaio** [comment]
thank *you* :rocket:

**Pull request merged**
