### PR TITLE
added usb_hid_mouse example for rp

### PR DESCRIPTION
**Pull request by mchant**

### CODE REVIEW

**Comment by Dirbaio** [comment]
can you fix CI?

**Comment by mchant** [comment]
I fixed what it complained about, but I can't figure out how to rerun the check.

**Review by mchant — COMMENTED** [review]
updated use declaration

**Comment by Dirbaio** [comment]
bender run

**Comment by Dirbaio** [comment]
can you please fix rustfmt too? thanks!

**Comment by Dirbaio** [comment]
you can fix formatting automatically by running `cargo fmt`. I also recommend enabling "format on save" in your IDE.

**Comment by mchant** [comment]
Sorry to spam the commits. I tried that originally, but it just prints
```
Warning: can't set `imports_granularity = Module`, unstable features are only available in nightly channel.
Warning: can't set `group_imports = StdExternalCrate`, unstable features are only available in nightly channel.
```
about 50 times in the terminal, and it doesn't update anything.

**Comment by Dirbaio** [comment]
ah yes, you have to use nightly rustfmt for those.

**Pull request merged**
