### PR TITLE
Allow ethernet and 802.15.4 to coexist

### PR DESCRIPTION
**Pull request by rubdos**
/cc @xoviat 

I had some duplicate work lying around with @xoviat's #1655 (and I still have some more), and this is part of the result of some rebase conflicts. @xoviat, to what extent are you planning to add sixlowpan to Embassy?

### CODE REVIEW

**Comment by Dirbaio** [comment]
is the issue a build failure when both `medium-ethernet` and `medium-ieee802154` features are enabled? If so, could you add a check to `ci.sh` so it doesn't break again?

**Comment by rubdos** [comment]
Yes indeed. It's not that we needed this, but we had that code lying around in this form...

**Review by Dirbaio — APPROVED** [review]
thanks!

**Comment by xoviat** [comment]
@rubdos it's partially implemented but a full implementation is whenever I get around to it.

**Pull request merged**
