### PR TITLE
Remove legacy LoRa drivers

### PR DESCRIPTION
**Pull request by ceekdee**
Remove legacy LoRa drivers and associated configuration.

### CODE REVIEW

**Comment by Dirbaio** [comment]
LGTM? is there anything left to do? :eyes:

**Comment by ceekdee** [comment]
Guidance would be appreciated on how to handle [package.metadata.embassy_docs] in embassy-lora/Cargo.toml.  This crate will now be used by several combinations of MCU and LoRa chip, so I am unclear if flavor is useful now and target is just one of several.  I modeled it after embassy-net/Cargo.toml, which presumably has similar issues.

**Comment by Dirbaio** [comment]
Yes, having no flavors looks good to me.

**Comment by ceekdee** [comment]
LGTM from my perspective.

**Pull request merged**
