### PR TITLE
Add ISO endpoint support

### PR DESCRIPTION
**Pull request by elagil**
Adds support for ISO endpoints for both the STM32 OTG USB driver and the "regular" (newer?) USB driver.

### CODE REVIEW

**Comment by elagil** [comment]
For anyone who is reviewing this, find the USB packet buffer layouts that I used. They are relevant for the functions that read/write from/to the `btable`. The values in the `btable` are the addresses of the software packet buffers, and the received/transmitted buffer sizes.

For double-buffered endpoints, both RX and TX count and address fields are used for THE SAME direction (either RX or TX, never both). I hope that is clear from the comments in the code as well.

From RM0481 (STM32H5)
image

From RM0091 (STM32F0x1)
image

**Comment by M3gaFr3ak** [comment]
This is a very important PR to make embassy usable for any audio-related USB stuff. I'm currently implementing USB Audio 2.0 and thanks to this PR, I have a successfully enumerating and streaming device!
When I'm finished, I'll try to PR an example.

**Comment by elagil** [comment]
@M3gaFr3ak I agree, that is what I needed it for. Very curious to see your UAC 2.0 implementation. I made UAC 1.0 in https://github.com/embassy-rs/embassy/pull/3212

**Review by Dirbaio — APPROVED** [review]
thank you! looking great

**Comment by M3gaFr3ak** [comment]
@elagil This is the test implementation I'm currently doing: https://github.com/M3gaFr3ak/rp-usb-uac2
It's only using full speed, but that's enough for demoing. I don't actually do proper handling, it currently enumerates and the endpoints receive data. I've also modified embassy-usb to allow reuse of endpoints https://github.com/embassy-rs/embassy/issues/2994
I'll continue working on this until i have a loopback device working (speaker to mic)

**Pull request merged**
