### PR TITLE
wip: fmac

### PR DESCRIPTION
**Pull request by xoviat**
This needs changes to stm32-data before moving forward.

### CODE REVIEW

**Comment by okhsunrog** [comment]
@xoviat is the PR abandoned? Seems like FMAC is merged into stm32-data

**Comment by Dirbaio** [comment]
it's abandoned, feel free to pick it up

**Comment by xoviat** [comment]
Yeah, I've been busy with other matters. Feel free to take this forward

**Comment by Dirbaio** [comment]
closing since this is an empty skeleton.

**Pull request closed without merging**
