### PR TITLE
Allow potentially unused import

### PR DESCRIPTION
**Pull request by bsodmike**
Replaces #2860

### CODE REVIEW

**Comment by bsodmike** [comment]
@Dirbaio I saw your "?" mark in the channel, just to clarify - when I had vendored a fork of Embassy, I saw 

```rust
warning: the item `AtomicWaker` is imported redundantly
 --> vendor/embassy/embassy-stm32/src/usart/buffered.rs:5:5
  |
5 | use embassy_sync::waitqueue::AtomicWaker;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6 |
7 | use super::*;
  |     -------- the item `AtomicWaker` is already imported here
  |
  = note: `#[warn(unused_imports)]` on by default
```
but I also saw once CI ran that tests would import this separately without a dependency on `super::*` - so it's needed.

This is just to silence the above warning.

**Comment by Dirbaio** [comment]
under which condition is it unused? afaict it's used unconditionally in `State`.

If it's redundant due to the `use super::*;` maybe we should remove that instead, replacing it with `use super::{list, of, things};`

**Comment by Dirbaio** [comment]
done in #2872

**Comment by bsodmike** [comment]
> under which condition is it unused? afaict it's used unconditionally in `State`.
> 
> 
> 
> If it's redundant due to the `use super::*;` maybe we should remove that instead, replacing it with `use super::{list, of, things};`

Thanks for the suggestion!!

**Pull request closed without merging**
