### PR TITLE
docs: add esp-hal

### PR DESCRIPTION
**Pull request by MabezDev**
I can also add some examples if you think that is a good idea, but I don't want to add any maintenance burden in doing so; of course, I am more than happy to maintain the examples myself.

### CODE REVIEW

**Review by lulf — APPROVED** [review]
Makes sense I think, thanks for adding it!

bors r+

**Comment by Dirbaio** [comment]
Adding a "dummy" `embassy-esp` directory feels a bit strange. I think the note in the top-level README should be enough.

**Comment by Dirbaio** [comment]
Thanks!

**Pull request merged**
