### PR TITLE
low-power: add support for stm32u0

### PR DESCRIPTION
**Pull request by chrenderle**
Adding low-power support for the stm32u0. This PR depends on embassy-rs/stm32-data#540.

I can measure ~9uA for a blinky with 0.5Hz LED frequency. During stop the power consumption is ~2uA when the LED is off. The measurements are on my Nucleo-U083RC.
low-power-stop2-u0
low-power-stop2-u0-2

### CODE REVIEW

**Comment by chrenderle** [comment]
Now all errors should be fixed apart from those depending on the PR.

**Review by Dirbaio — APPROVED** [review]
thanks!

**Comment by Dirbaio** [comment]
is the ci failure is due to stm32-metapac needing updating? you can do it by changing the commit hash in Cargo.toml (in two places)

**Comment by chrenderle** [comment]
> is the ci failure is due to stm32-metapac needing updating? you can do it by changing the commit hash in Cargo.toml (in two places)

yes, the errors are because of the stm32-metapac update. I will change the hashes

**Comment by chrenderle** [comment]
@Dirbaio do I just take the latest hash or the one with the changes I need?

**Comment by Dirbaio** [comment]
ideally latest!

**Pull request merged**
