### PR TITLE
Typestate nrf timer

### PR DESCRIPTION
**Pull request by fnafnio**
useful for hooking up the PPI to an Event without needing interrupt
tested with buffered_uart example on nRF52840-DK

the names are aweful but descriptive, I'm very open to suggestions

### CODE REVIEW

**Comment by fnafnio** [comment]
Of course some docs on the differences and use cases should be added, like suggesting to set a short on something like clear counter

**Comment by Dirbaio** [comment]
Yeah, naming for this is quite something... I can't think of anything better either :S 

Perhaps the type aliases are not necessary? especially since the Cc struct doesn't have corresponding type aliases. They don't gain you much, `Timer<TIMER3, NotAwaitable>` is the same length as `NotAwaitableTimer<TIMER3>`...

We could also use default generic params, the default should probably be NotAwaitable. This way, the user would write `Timer<TIMER3>` for not awaitable, and `Timer<TIMER3, Awaitable>`

Another thing: if both `new` methods are named equally, the compiler will reject `Timer::new` as ambiugous. Perhaps they should be `new` and `new_awaitable`? especially if we remove the type aliases.

**Comment by fnafnio** [comment]
I've implemented the suggestions and added an example for the awaitable timer.
Having less redundancy definitely improves the feel

I guess for the not awaitable timer the comment leading one to the uarte implementation should be enough?

**Review by Dirbaio — APPROVED** [review]
Awesome, thank you!

Yeah, docs look good, and we can always improve them later.

**Pull request merged**
