### PR TITLE
Add example for sharing things between tasks

### PR DESCRIPTION
**Pull request by kalkyl**
We get a lot of questions about how to share things between tasks, so i thought an example would be a good idea, showcasing some common scenarios.

### CODE REVIEW

**Comment by jamesmunns** [comment]
Very happy to have this! Might make sense to do some cross linking with these docs pages for better discoverability:

* https://embassy.dev/book/#_sharing_peripherals_between_tasks
* https://embassy.dev/book/#_multiple_tasks_or_one_task_with_multiple_futures

**Review by jamesmunns — APPROVED** [review]
Happy to have this! Added some comments for potentially making this more discoverable.

It might be worth adding a top level doc-comment comparing and contrasting the demonstrated concurrency:

"We demonstrate three different ways of sharing in this example:"

* This is shared via a Cell, this is useful for ...
* This is shared via a RefCell, this is useful for ...
* This is shared via a Mutex, this is useful for ...

**Comment by kalkyl** [comment]
> Happy to have this! Added some comments for potentially making this more discoverable.
> 
> It might be worth adding a top level doc-comment comparing and contrasting the demonstrated concurrency:
> 
> "We demonstrate three different ways of sharing in this example:"
> 
> * This is shared via a Cell, this is useful for ...
> * This is shared via a RefCell, this is useful for ...
> * This is shared via a Mutex, this is useful for ...

Good idea, added some more info and links!

**Comment by jamesmunns** [comment]
Thanks, this looks great!

**Pull request merged**
