### PR TITLE
Add DAC v3

### PR DESCRIPTION
**Pull request by JuliDi**
Based on the PRs https://github.com/embassy-rs/embassy/pull/1676 and https://github.com/embassy-rs/embassy/pull/1677, this adds DAC v3 (available in stm32-metapac v13, https://github.com/embassy-rs/stm32-data/pull/223) for the STM32H7 and some others that previously had no support for DMA in the DAC implementation.

### CODE REVIEW

**Comment by JuliDi** [comment]
Seems to be working fine on the STM32H7A3

**Comment by Dirbaio** [comment]
LGTM to the DAC changes. Can you take out the unrelated DMA changes? Thanks!

**Comment by JuliDi** [comment]
> LGTM to the DAC changes. Can you take out the unrelated DMA changes? Thanks!

Not sure why exactly they are in there now (some of them need to be to match the transfer options, but for the others I will remove them and test again).

**Comment by Dirbaio** [comment]
oh sorry I didn't look hard enough. I see the DMA changes are to match the flags that already exist on BDMA. I thought they were unrelated, since I didn't see new DAC code using them. Sorry! LGTM them.

**Comment by JuliDi** [comment]
I also just checked again and it looks like all of them are needed. Should be good to go.

**Pull request merged**
