### PR TITLE
Bootloader external flash

### PR DESCRIPTION
**Pull request by lulf**
Includes e-s and e-s-a impls for nrf QSPI

WIP: Working on testing it.

### CODE REVIEW

**Comment by lulf** [comment]
Relies on #723

**Comment by Dirbaio** [comment]
@lulf is it still WIP or not anymire?

**Comment by lulf** [comment]
@Dirbaio no more WIP, ready for review.

**Comment by lulf** [comment]
Merging now. Will add some more documentation to the book and refactor the example structure a bit in a later PR. Also working on stm32 support.

bors r+

**Pull request merged**
