### PR TITLE
Use stm32-metapac for BXCAN.

### PR DESCRIPTION
**Pull request by cschuhen**
1. Copy bxcan crate into hal
2. Make it work with internal crate
3. Port register access to stm32-metapac
4. Remove bxcan internal PAC.

### CODE REVIEW

**Comment by cschuhen** [comment]
@Dirbaio, When you get a chance, can I get trusted on this please?

**Comment by cschuhen** [comment]
@Dirbaio, I tried my best to split the commits up to make it easy to review. If you want, I can collapse some of them before  merging.

- The first 4 changesets really just copy in the bxcan crate and get it working. Should be pretty much exactly binary compatible. Mainly things like module 'paths' and imports. 
- The changeset with title "Port registers access to using Embassy PAC" is the meat of this PR. It's the part that was manual and I could have stuffed something up.
- The last two just clean a couple of things up and get it passing stuff.

**Comment by Dirbaio** [comment]
is this ready for review (asking because PR title still says "draft")

**Comment by cschuhen** [comment]
Yes, you are right. I forgot to do the filters module and then forgot to remove the bxcan crate's internal PAC after it was working with stm32-metapac. I have pushed updates, it should be ready to review now.

**Comment by cschuhen** [comment]
b.t.w. The current build failures seem unrelated.

**Comment by cschuhen** [comment]
Please note, I have pushed another branch to my repo that represents a 'squashed down' version of this PR:
https://github.com/embassy-rs/embassy/compare/main...cschuhen:embassy:feature/bxcan_pac_collapsed
Probably bxcan_pac_collapsed is better for actual merge but bxcan_pac is better for review purposes (and my development if further changes are required) Both arrive at the same destination.

**Review by Dirbaio — APPROVED** [review]
thanks!

**Comment by cschuhen** [comment]
Thank-you!

**Pull request merged**
