### PR TITLE
feat: embassy-usb-logger and example for rpi pico

### PR DESCRIPTION
**Pull request by lulf**
* Add embassy-usb-logger which allows logging over USB for any device implementing embassy-usb
* Add example using logger for rpi pico

### CODE REVIEW

**Comment by lulf** [comment]
@chrta I see that the usb_serial.rs example for nRF also enables the high frequency clock this way:

```
    let clock: pac::CLOCK = unsafe { core::mem::transmute(()) };

    clock.tasks_hfclkstart.write(|w| unsafe { w.bits(1) });
    while clock.events_hfclkstarted.read().bits() != 1 {}

```

could you try adding that raight after embassy_nrf::init()?

**Comment by chrta** [comment]
Thank you for the hint. I could not use `embassy_nrf::pac`, since it is not public, but i enabled the external xtal as a clock source via config parameter of `embassy_nrf::init()`. According to my very limited rust knowledge it should do basically the same.

But i still get the same build error:
```
error[E0277]: the trait bound `embassy_nrf::usb::Driver<'_, embassy_nrf::peripherals::USBD, PowerUsb>: embassy_usb_driver::Driver<'_>` is not satisfied
   --> usb_logger/src/main.rs:13:5
    |
13  |     embassy_usb_logger::run!(1024, log::LevelFilter::Info, driver);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |     |
    |     the trait `embassy_usb_driver::Driver<'_>` is not implemented for `embassy_nrf::usb::Driver<'_, embassy_nrf::peripherals::USBD, PowerUsb>`
    |     required by a bound introduced by this call
    |
help: trait impl with same name found
   --> /home/user/.cargo/git/checkouts/embassy-9312dcb0ed774b29/2528f45/embassy-nrf/src/usb.rs:232:1
    |
232 | impl<'d, T: Instance, P: UsbSupply + 'd> driver::Driver<'d> for Driver<'d, T, P> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `embassy_usb_driver` are being used?
note: required by a bound in `UsbLogger::<N>::run`
   --> /home/user/.cargo/git/checkouts/embassy-87335ae8f9b89537/a444a65/embassy-usb-logger/src/lib.rs:52:12
    |
52  |         D: Driver<'d>,
    |            ^^^^^^^^^^ required by this bound in `UsbLogger::<N>::run`
    = note: this error originates in the macro `embassy_usb_logger::run` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `xiao-nfr52840-async-usb-logger-example` due to previous error
```

**Comment by diegoasanch** [comment]
@lulf Awesome feature, thank you for implementing this!

**Comment by diegoasanch** [comment]
@chrta I got the same error when testing this feature. The fix was to change the `embassy-*` dependencies on the `Cargo.toml` file to this specific branch so that all embassy code is coming from the same crate. e.g:
```
embassy-rp = { version = "0.1.0", git = "https://github.com/lulf/embassy", branch = "usb-logger", features = [...], package="embassy-rp" }
```

 I'm not that experienced with Rust, but my understading is that since the implementation is still not on the `embassy-rs:master` branch the compiler might be preventing the crate from `lulf:usb-logger` from implementing a trait on the `embassy-rs:main` crate which is [not allowed](https://doc.rust-lang.org/book/ch10-02-traits.html#:~:text=But%20we%20can%E2%80%99t,implementation%20to%20use.).

**Comment by chrta** [comment]
@diegoasanch Great, thank you. It builds now.

**Comment by Dirbaio** [comment]
Thanks @lulf, this is a great addition to the toolbox! :D

bors r+

**Pull request merged**
