### PR TITLE
embassy-stm32/pwm: Generalize channel selection

### PR DESCRIPTION
**Pull request by bgamari**
550da471be7b56927b50b5955a6de0916ebe6b1f previously refactored the STM32
PWM logic in such a way to preclude use of non-contiguous channels (e.g.
channel 2 but not channel 1). Refactor it yet again to yet again allow
this sort of usage.

### CODE REVIEW

**Comment by Dirbaio** [comment]
LGTM, feel free to merge yourself when CI passes! :) 

bors d+

**Comment by bgamari** [comment]
Bah, looks like this is already conflicting.

**Comment by Yatekii** [comment]
Hey, would you mind rebasing this once more or should I try the undertaking? :)

**Comment by Dirbaio** [comment]
Hmm, there's one usability issue. If you try to use it the obvious way, you get a weird compiler error. Even though the compiler can deduce `ch1` must be of type `PwmPin<TIM1, Ch1>` it's not smart enough to know which `new` to pick from that :thinking: 

```rust
    let ch1 = PwmPin::new(p.PE9);
    let mut pwm = SimplePwm::new(p.TIM1, Some(ch1), None, None, None, khz(10));
```
```
error[E0034]: multiple applicable items in scope
  --> src/bin/pwm.rs:18:23
   |
18 |     let ch1 = PwmPin::new(p.PE9);
   |                       ^^^ multiple `new` found
   |
   = note: candidate #1 is defined in an impl for the type `PwmPin<'d, Perip, embassy_stm32::pwm::simple_pwm::Ch1>`
   = note: candidate #2 is defined in an impl for the type `PwmPin<'d, Perip, embassy_stm32::pwm::simple_pwm::Ch2>`
   = note: candidate #3 is defined in an impl for the type `PwmPin<'d, Perip, embassy_stm32::pwm::simple_pwm::Ch3>`
   = note: candidate #4 is defined in an impl for the type `PwmPin<'d, Perip, embassy_stm32::pwm::simple_pwm::Ch4>`
```

**Comment by Dirbaio** [comment]
I've renamed `new` to `new_ch1, new_ch2...`. Not ideal, but better than the most basic API use case requiring turbofish.

bors r+

**Pull request merged**
