### PR TITLE
Add `PLL1_P_MUL_2` clock.

### PR DESCRIPTION
**Pull request by OroArmor**
See: https://github.com/embassy-rs/embassy/pull/2583#issuecomment-1963115182

Waiting on a data pr.

### CODE REVIEW

**Comment by Dirbaio** [comment]
LGTM. 

For it to have effect you have to update stm32-metapac in Cargo.toml tho

**Comment by OroArmor** [comment]
Yep! I was just double checking the code was generated correctly.

**Review by Dirbaio — APPROVED** [review]
thanks!

**Comment by OroArmor** [comment]
Somehow updating something, I'm guessing the metapac, caused some other code to fail to build. No clue what went wrong.

**Pull request merged**
