### PR TITLE
Add STM32WB55

### PR DESCRIPTION
**Pull request by eupn**
This PR adds initial STM32WB55 support with a primary focus on BLE, but also adds an async I2C with DMA.

Beacon example was tested in hardware:

image

### CODE REVIEW

**Comment by Dirbaio** [comment]
Sorry for the delay in reviewing this! I'm waiting for a nucleo-wb55 to arrive :)

**Comment by Dirbaio** [comment]
I finally received the nucleo-wb55 and got to test this out!

First of all, very impressive work, both on your stm32wb crates and the embassy integration! The BLE example worked flawlessly :D

Some notes from a quick look at the code:

---

 `nb` should not appear at all on the BLE public API. A WouldBlock error doesn't make sense in async code. A function never returns WouldBlock, it just waits for whatever to finish.

---

 I'm not a fan of fixed-size queues, like the `deferred_events` queue. They can overflow and take down the entire firmware. With the current API it seems to me that if the user never calls `receive_event` then non-response events will accumulate the queue until it crashes. It's also not possible to call `receive_event` from one task concurrently with `perform_command` from another.

In `nrf-softdevice` I had similar problems, and the solution I found was to spawn a [task processing events](https://github.com/akiles/nrf-softdevice/blob/e6a75b927199ce0ea2f22cd6e19d7aa878bbd474/nrf-softdevice/src/events.rs#L51), then depending on the type of the event they're [delivered to the correct Portal](https://github.com/akiles/nrf-softdevice/blob/e6a75b927199ce0ea2f22cd6e19d7aa878bbd474/nrf-softdevice/src/ble/gap.rs#L26), which the task doing the operation is [waiting](https://github.com/akiles/nrf-softdevice/blob/e6a75b927199ce0ea2f22cd6e19d7aa878bbd474/nrf-softdevice/src/ble/central.rs#L64). 

I think a similar design could work here. The event-processing task could deliver `CommandComplete` events to `perform_command` via a Portal, and processes other event kinds in other ways as they come in, without having to queue them?

---

the LpTimer should implement embassy::traits::delay::Delay, instead of async_embedded_traits::delay

---

Something I noticed is the binary size of the ble example is quite high: 113.3KiB

Adding build-std=core, build-std-features=panic_immediate_abort brings that down to 57.7KiB, which is still quite high.

Checking with `cargo bloat` shows this:

```
File  .text    Size                Crate Name
2.1%  59.8% 34.5KiB        bluetooth_hci bluetooth_hci::event::Event<V>::new
0.8%  23.7% 13.7KiB ble_eddystone_beacon ble_eddystone_beacon::run::task::{{closure}}
0.1%   3.2%  1.8KiB                 core <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
0.1%   1.9%  1.1KiB            stm32wb55 <bluetooth_hci::Status<V> as core::convert::TryFrom<u8>>::try_from
0.0%   1.1%    636B              embassy embassy::executor::Executor::run
0.0%   1.0%    606B        bluetooth_hci bluetooth_hci::types::connection_interval::ConnectionIntervalBuilder::build
0.0%   0.8%    490B    compiler_builtins compiler_builtins::int::specialized_div_rem::u64_div_rem
0.0%   0.5%    294B    embassy_stm32wb55 embassy_stm32wb55::ble::Ble::on_rx_irq
0.0%   0.5%    294B ble_eddystone_beacon ble_eddystone_beacon::__cortex_m_rt_main
0.0%   0.5%    266B            defmt_rtt <defmt_rtt::Logger as defmt::Write>::write
0.0%   0.4%    238B        bluetooth_hci bluetooth_hci::types::connection_interval::FixedConnectionInterval::from_bytes
0.0%   0.4%    212B          stm32wb_hal stm32wb_hal::rtc::Rtc::rtc
0.0%   0.4%    212B              embassy embassy::executor::Task<F>::poll
0.0%   0.3%    194B          stm32wb_hal stm32wb_hal::tl_mbox::lhci::LhciC1DeviceInformationCcrp::new
0.0%   0.3%    186B            stm32wb55 stm32wb55::event::command::to_gatt_handle_value
0.0%   0.3%    164B    embassy_stm32wb55 embassy_stm32wb55::ble::Ble::on_tx_irq
0.0%   0.3%    154B           stm32wb55? <stm32wb55::RadioCoprocessor<N> as bluetooth_hci::Controller>::peek
0.0%   0.2%    142B            stm32wb55 <stm32wb55::RadioCoprocessor<N> as stm32wb55::command::gap::Commands>::update_advertising_data
0.0%   0.2%    140B           stm32wb55? <stm32wb55::RadioCoprocessor<N> as bluetooth_hci::Controller>::write
0.0%   0.2%    138B              bbqueue bbqueue::bbbuffer::Consumer<N>::read
0.1%   4.1%  2.3KiB                      And 63 smaller methods. Use -n N to show more.
3.5% 100.0% 57.7KiB                      .text section size, the file size is 1.6MiB
```

60% of the binary is Event::new, which is deserializing HCI event bytes into Rust structs/enums.... This is not in our scope to fix, but wanted to highlight it.

**Comment by eupn** [comment]
@Dirbaio thanks a lot for an extended review and comments!

>nb should not appear at all on the BLE public API. A WouldBlock error doesn't make sense in async code. A function never returns WouldBlock, it just waits for whatever to finish.

Sure, I overlooked this.

>I'm not a fan of fixed-size queues, like the deferred_events queue. They can overflow and take down the entire firmware. With the current API it seems to me that if the user never calls receive_event then non-response events will accumulate the queue until it crashes. It's also not possible to call receive_event from one task concurrently with perform_command from another.

The only reason for that queue is to be able to receive a command response while being able to receive and process unsolicited events. It's like a priority queue with command responses being the top priority but only if somebody waiting for them at the moment.

>In nrf-softdevice I had similar problems, and the solution I found was to spawn a task processing events, then depending on the type of the event they're delivered to the correct Portal, which the task doing the operation is waiting.

Wow, lmao how I just missed all that `Portal` thing which is pretty useful. I'll definitely try to replicate your approach.

>the LpTimer should implement embassy::traits::delay::Delay, instead of async_embedded_traits::delay

At the time this timer was implemented, there weren't built-in delay traits yet. It should be straightforward to implement them too.

>60% of the binary is Event::new, which is deserializing HCI event bytes into Rust structs/enums.... This is not in our scope to fix, but wanted to highlight it.

That's quite a lot, thanks for pointing this out!

**Comment by eupn** [comment]
Closing this as the code has drifted away too much. I'd possibly spend some time porting this to a newer STM32 support shipped by Embassy.

**Pull request closed without merging**
